
import { Badge, Player, PlayerStatus, Position } from './types';

export const ADMIN_NICKNAMES = ['tonoli', 'cleitim', 'markin', 'cleiton', 'marquinho', 'marquinhos'];

export const ALL_BADGES: Badge[] = [
  // --- LEGADO, HONRA & AUTORIDADE (TOP TIER) ---
  { id: 'teg1', name: 'TEG - Esquadrão Grená', icon: '/badges/teg.png', description: 'Espancador de rio branquense. Traje de gala é a peita da organizada.', category: 'Elite' },
  { id: 'leg1', name: 'Fundador da Pelada', icon: '👑', description: 'O patriarca que começou tudo isso aqui. Respeite o ancião.', category: 'Elite' },
  { id: 'leg2', name: 'Administrador da Biqueira', icon: '👮‍♂️', description: 'Quem manda nessa porra. A palavra final é dele.', category: 'Elite' },
  { id: 'leg3', name: 'Bola de Ouro Suprema', icon: '🥇', description: 'O ápice da excelência técnica e moral. O melhor dos melhores.', category: 'Elite' },
  { id: 'dev1', name: 'Mago do Código', icon: '🧙‍♂️', description: 'O mago que fez essa porra toda, o mágico da programação', category: 'Architect' },
  { id: 'leg4', name: 'Sócio Vitalício', icon: '🎟️', description: 'Parte inseparável da história desse bueiro.', category: 'Elite' },
  { id: 'leg5', name: 'Embaixador da Várzea', icon: '🌍', description: 'Leva o nome do FDP por onde passa.', category: 'Elite' },

  // --- ORIGINAIS & FUNDAMENTAIS ---
  { id: 'b1', name: 'Chegou Agora', icon: '👶', description: 'Acabou de brotar. Fica esperto pra não virar saudade.', category: 'Geral' },
  { id: 'b9', name: 'Sobrevivente', icon: '💀', description: 'Jogou a primeira sem vomitar nem apanhar.', category: 'Geral' },
  { id: 'b2', name: 'Sócio da Boca', icon: '🖐️', description: '5 peladas. Já deve dinheiro pra todo mundo.', category: 'Geral' },
  { id: 'b3', name: 'Procurado', icon: '🚔', description: 'Sumiu. Ou tá preso ou tá devendo pensão.', category: 'Geral' },
  { id: 'b4', name: 'Zumbi', icon: '🧟', description: 'Ressuscitou das cinzas cheio de cachaça.', category: 'Geral' },
  { id: 'b5', name: 'Pulmão de Filtro', icon: '🚬', description: 'Não corre 2 metros, só fica fumando na beira do campo.', category: 'Geral' },
  { id: 'b6', name: 'Perna de Pau', icon: '🪵', description: 'É ruim com força. Dá desgosto de ver.', category: 'Geral' },
  { id: 'b7', name: 'Dono da Várzea', icon: '👑', description: '100 jogos. O fígado já pediu demissão.', category: 'Geral' },
  { id: 'b8', name: 'Chorão', icon: '😭', description: 'Reclama de tudo. Acha que tá na Champions, seu lixo?', category: 'Geral' },
  { id: 'sp_unique_brow', name: 'Brow Único', icon: '/badges/no-monkey.png', description: 'Macacos são proibidos na pelada, mas o brow é UNICO!', category: 'Elite' },
  { id: 'mk1', name: 'Mesmo proibido ele esta presente na pelada', icon: '/badges/no-monkey.png', description: 'Ele viu tudo, mas não vai falar nada. O infiltrado do bueiro.', category: 'Elite' },

  // --- PRESENÇA & FIDELIDADE ---
  { id: 'pres1', name: 'Calouro do Bueiro', icon: '👶', description: 'Veio na primeira pelada. Não morreu ainda.', category: 'Geral' },
  { id: 'pres2', name: 'Habitué da Várzea', icon: '🏃', description: '5 jogos confirmados. Já sabe onde é o banheiro.', category: 'Geral' },
  { id: 'pres3', name: 'Sócio-Torcedor', icon: '🎟️', description: '10 jogos. O porteiro já te cumprimenta.', category: 'Geral' },
  { id: 'pres4', name: 'Veterano de Guerra', icon: '🎖️', description: '20 jogos. Já viu muita canelada nessa vida.', category: 'Geral' },
  { id: 'pres5', name: 'Patrimônio Histórico', icon: '🏛️', description: '50 jogos. Faz parte da mobília da pelada.', category: 'Geral' },
  { id: 'pres6', name: 'Estátua de Vantablack', icon: '🗿', description: '100 jogos. Inamovível, lendário, cansado.', category: 'Geral' },
  { id: 'pres7', name: 'Fosforescente', icon: '✨', description: 'Nunca faltou em um mês inteiro.', category: 'Geral' },
  { id: 'pres8', name: 'Coração de Ferro', icon: '❤️', description: 'Veio jogar até debaixo de tempestade.', category: 'Geral' },
  { id: 'pres9', name: 'Inimigo da Folga', icon: '🚫', description: 'Joga até no feriado de Natal.', category: 'Geral' },
  { id: 'pres10', name: 'Turista Espacial', icon: '🚀', description: 'Sumiu por 6 meses e reapareceu do nada.', category: 'Geral' },
  { id: 'pres11', name: 'Vampiro', icon: '🧛', description: 'Só joga se for a pelada da noite.', category: 'Geral' },
  { id: 'pres12', name: 'Bifásico', icon: '🔌', description: 'Joga duas peladas seguidas sem infartar.', category: 'Geral' },
  { id: 'pres13', name: 'Sombra', icon: '👤', description: 'Vem, joga, não fala com ninguém e some.', category: 'Geral' },
  { id: 'pres14', name: 'Arauto do Jogo', icon: '📣', description: 'O primeiro a confirmar no grupo toda semana.', category: 'Geral' },
  { id: 'pres15', name: 'Último dos Moicanos', icon: '🏹', description: 'O último a confirmar, sempre no susto.', category: 'Geral' },
  { id: 'pres16', name: 'Fiel Escudeiro', icon: '🛡️', description: 'Sempre traz um convidado pra completar o time.', category: 'Geral' },
  { id: 'pres17', name: 'Fura-Bolo Profissional', icon: '🎂', description: 'Confirmou e não veio 3 vezes seguidas. Lixo.', category: 'Geral' },
  { id: 'pres18', name: 'Ressuscitado', icon: '✝️', description: 'Voltou a jogar depois de uma lesão de 1 ano.', category: 'Geral' },
  { id: 'pres19', name: 'Onipresente', icon: '🌌', description: 'Está em todas as fotos da galeria, sem exceção.', category: 'Geral' },
  { id: 'pres20', name: 'Viajante do Tempo', icon: '⏳', description: 'Chega sempre 30 min antes da pelada começar.', category: 'Geral' },
  { id: 'pres21', name: 'Atrasado Crônico', icon: '⏰', description: 'O jogo começa às 20h, ele chega às 21h.', category: 'Geral' },
  { id: 'pres22', name: 'Mestre do W.O.', icon: '❌', description: 'Fez o time perder por falta de quórum.', category: 'Geral' },
  { id: 'pres23', name: 'Guerreiro de Segunda', icon: '📅', description: 'Só joga se for na segunda-feira.', category: 'Geral' },
  { id: 'pres24', name: 'Nômade', icon: '🏜️', description: 'Joga em 5 peladas diferentes por semana.', category: 'Geral' },
  { id: 'pres25', name: 'Âncora', icon: '⚓', description: 'Mantém o grupo unido quando todo mundo quer sair.', category: 'Geral' },
  { id: 'pres26', name: 'Frequência 2k', icon: '📻', description: 'Veio em 200 jogos. Sua pele já é sintética.', category: 'Geral' },
  { id: 'pres27', name: 'O Guardião das Chaves', icon: '🔑', description: 'Sempre chega antes do zelador.', category: 'Geral' },
  { id: 'pres28', name: 'Fechador de Porteira', icon: '🔒', description: 'O último a sair do campo em 10 jogos.', category: 'Geral' },
  { id: 'pres29', name: 'Inimigo da Família', icon: '🚫', description: 'Sempre troca o almoço de domingo pelo fut.', category: 'Geral' },
  { id: 'pres30', name: 'Morador do Bueiro', icon: '🏠', description: 'Parece que dorme no centro de treinamento.', category: 'Geral' },
  { id: 'pres31', name: 'Nômade Digital', icon: '💻', description: 'Participa do grupo mesmo quando viaja.', category: 'Geral' },
  { id: 'pres32', name: 'Reserva de Luxo', icon: '🛋️', description: 'Só entra se alguém cansar, mas não falta.', category: 'Geral' },
  { id: 'pres33', name: 'Sombra da Segunda', icon: '🌑', description: 'Aparece toda segunda faça chuva ou faça sol.', category: 'Geral' },
  { id: 'pres34', name: 'Atleta de Cristo', icon: '⛪', description: 'Vem direto do culto pra pelada.', category: 'Geral' },
  { id: 'pres35', name: 'Bebê de Campo', icon: '🍼', description: 'O mais novo da pelada por 5 jogos seguidos.', category: 'Geral' },

  // --- FINANCEIRO & CAIXINHA ---
  { id: 'fin1', name: 'Pagador de Elite', icon: '💳', description: 'Paga a mensalidade antes do ADM cobrar.', category: 'Geral' },
  { id: 'fin2', name: 'Dívida Ativa', icon: '💸', description: 'Deve 3 meses. Tá quase virando dono do campo.', category: 'Geral' },
  { id: 'fin3', name: 'Mãos de Tesoura', icon: '✂️', description: 'Sempre pede desconto pra jogar.', category: 'Geral' },
  { id: 'fin4', name: 'Patrocinador Master', icon: '🏦', description: 'Pagou o churrasco sozinho uma vez.', category: 'Geral' },
  { id: 'fin5', name: 'Inimigo do Pix', icon: '📱', description: 'O celular sempre "trava" na hora de pagar.', category: 'Geral' },
  { id: 'fin6', name: 'Boleto Vencido', icon: '📄', description: 'Vive prometendo pagar "amanhã".', category: 'Geral' },
  { id: 'fin7', name: 'Tesoureiro Assistente', icon: '💰', description: 'Ajuda o ADM a cobrar os outros caloteiros.', category: 'Geral' },
  { id: 'fin8', name: 'Mão Aberta', icon: '🤲', description: 'Pagou a pelada de um amigo que tava sem grana.', category: 'Geral' },
  { id: 'fin9', name: 'Pão Duro de Ouro', icon: '🥖', description: 'Não paga nem a água que bebe.', category: 'Geral' },
  { id: 'fin10', name: 'Magnata da Várzea', icon: '💎', description: 'Sempre traz notas de 100 pra pagar 20 reais.', category: 'Geral' },

  // --- COMPORTAMENTO & RESENHA ---
  { id: 'bh1', name: 'Psicopata do Campo', icon: '🔪', description: 'Briga até com o gandula.', category: 'Geral' },
  { id: 'bh2', name: 'Lobo Solitário', icon: '🐺', description: 'Não passa a bola nem que o mundo acabe.', category: 'Geral' },
  { id: 'bh3', name: 'Coach de Várzea', icon: '📋', description: 'Quer dar tática mas não corre 1 km.', category: 'Geral' },
  { id: 'bh4', name: 'Inimigo da Paz', icon: '🤬', description: 'Xinga o próprio time o tempo todo.', category: 'Geral' },
  { id: 'bh5', name: 'Anjo do Bueiro', icon: '😇', description: 'Pede desculpa depois de dar o rapa.', category: 'Geral' },
  { id: 'bh6', name: 'Fumante de Elite', icon: '🚬', description: 'Fuma um cigarro no intervalo sem cansar.', category: 'Geral' },
  { id: 'bh7', name: 'Sommelier de Cerveja', icon: '🍺', description: 'Entende tudo de breja, nada de bola.', category: 'Geral' },
  { id: 'bh8', name: 'DJ da Pelada', icon: '📻', description: 'Traz a JBL pra tocar pagode sofrido.', category: 'Geral' },
  { id: 'bh9', name: 'Mestre do Churrasco', icon: '🥩', description: 'Joga mal mas faz uma picanha nota 10.', category: 'Geral' },
  { id: 'bh10', name: 'Chorão de Ouro', icon: '😢', description: 'Chorou por um lateral aos 2 min de jogo.', category: 'Geral' },
  { id: 'bh11', name: 'Rei do Mimimi', icon: '🤡', description: 'Acha que tudo é falta.', category: 'Geral' },
  { id: 'bh12', name: 'Fingidor', icon: '🎭', description: 'Cai sozinho e pede pênalti.', category: 'Geral' },
  { id: 'bh13', name: 'Silencioso', icon: '🙊', description: 'Não abriu a boca o jogo inteiro.', category: 'Geral' },
  { id: 'bh14', name: 'Motorista do Time', icon: '🚗', description: 'Traz 4 marmanjos no carro toda semana.', category: 'Geral' },
  { id: 'bh15', name: 'Almoxarife', icon: '🎒', description: 'Sempre traz a bomba e o colete pro jogo.', category: 'Geral' },

  // --- HABILIDADE: ATAQUE (LOG DE FEITOS) ---
  { id: 'atk1', name: 'Matador de Aluguel', icon: '🎯', description: 'Tocou na bola dentro da área? É gol.', category: 'Linha' },
  { id: 'atk2', name: 'Mestre das Canetas', icon: '🖊️', description: 'O rei do bueiro. 3 canetas no mesmo jogo.', category: 'Linha' },
  { id: 'cn1', name: 'Caneteiro Nível 1', icon: '🖊️', description: 'Deu sua primeira caneta oficial.', category: 'Linha' },
  { id: 'cn5', name: 'Caneteiro Nível 5', icon: '🖊️', description: 'Já distribuiu 5 canetas. Tá ficando abusado.', category: 'Linha' },
  { id: 'cn10', name: 'Caneteiro Nível 10', icon: '💉', description: '10 canetas. Os adversários fecham a perna quando você chega.', category: 'Linha' },
  { id: 'cn20', name: 'Caneteiro Nível 20', icon: '🪄', description: '20 canetas. Mestre da mágica entre as pernas.', category: 'Linha' },
  { id: 'cn50', name: 'Lenda das Canetas', icon: '👑', description: '50 canetas. Você é o terror do bueiro.', category: 'Linha' },

  { id: 'ch1', name: 'Dono do Chapéu', icon: '👒', description: 'Deu seu primeiro chapéu oficial.', category: 'Linha' },
  { id: 'ch5', name: 'Chapeleiro Maluco', icon: '🎩', description: '5 chapéus distribuídos. Joga com a bola no alto.', category: 'Linha' },
  { id: 'ch10', name: 'Mestre da Cobertura', icon: '🏠', description: '10 chapéus. Ninguém te alcança por cima.', category: 'Linha' },

  { id: 'db1', name: 'Dibre Humilhante', icon: '🐍', description: 'Deixou o cara no chão e saiu rindo.', category: 'Linha' },
  { id: 'db10', name: 'Entortador de Varal', icon: '🧺', description: '10 dribles desconcertantes confirmados.', category: 'Linha' },

  { id: 'atk4', name: 'Pé de Cristal', icon: '💎', description: 'Dribles finos e chutes precisos.', category: 'Linha' },
  { id: 'atk5', name: 'Artilheiro Raiz', icon: '⚽', description: 'Faz gol de canela, de orelha, de qualquer jeito.', category: 'Linha' },
  { id: 'atk6', name: 'Garçom de Luxo', icon: '🍷', description: '10 assistências em um único mês.', category: 'Linha' },
  { id: 'atk7', name: 'Bicicleta Sem Freio', icon: '🚲', description: 'Tentou uma bike e quase se matou.', category: 'Linha' },
  { id: 'atk8', name: 'Canhão de Vantablack', icon: '💣', description: 'Chute tão forte que furou a rede.', category: 'Linha' },
  { id: 'atk9', name: 'Falso 9', icon: '🕵️', description: 'Ninguém sabe onde ele tá, nem ele mesmo.', category: 'Linha' },
  { id: 'atk10', name: 'Pivô de Ferro', icon: '🏗️', description: 'Segura os zagueiros no peito.', category: 'Linha' },
  { id: 'atk11', name: 'Driblador de Cone', icon: '🚧', description: 'Dribla até a sombra mas não chuta.', category: 'Linha' },
  { id: 'atk12', name: 'Veloz e Furioso', icon: '🏎️', description: 'Só tem corida, zero técnica.', category: 'Linha' },
  { id: 'atk13', name: 'Mestre do Escanteio', icon: '🚩', description: 'Cobrou um escanteio direto pro gol.', category: 'Linha' },
  { id: 'atk14', name: 'Cabeça de Martelo', icon: '🔨', description: 'Ganha todas no alto.', category: 'Linha' },
  { id: 'atk15', name: 'Oportunista', icon: '🦊', description: 'Só faz gol de rebote.', category: 'Linha' },
  { id: 'atk16', name: 'Chute de Mula', icon: '🐴', description: 'Chute forte, sem direção, mas assusta.', category: 'Linha' },
  { id: 'atk17', name: 'Pé de Algodão', icon: '☁️', description: 'Passe tão macio que chega a ser suspeito.', category: 'Linha' },
  { id: 'atk18', name: 'Lobo Solitário IV', icon: '🐺', description: 'Ignorou o companheiro livre pela 10ª vez.', category: 'Linha' },
  { id: 'atk19', name: 'Carrasco do Goleiro', icon: '💀', description: 'Sempre faz gol no mesmo goleiro coitado.', category: 'Linha' },
  { id: 'atk20', name: 'Pé Torto de Ouro', icon: '🥨', description: 'Chutou pra lateral estando na cara do gol.', category: 'Linha' },
  { id: 'atk21', name: 'Mestre do drible curto', icon: '🐍', description: 'Dribla em uma moeda de 1 real.', category: 'Linha' },
  { id: 'atk22', name: 'Cabeça de Ouro', icon: '🥇', description: 'Fez 3 gols de cabeça no mesmo mês.', category: 'Linha' },
  { id: 'atk23', name: 'Fominha de Carteirinha', icon: '🍔', description: 'Ganhou o prêmio fominha 3 vezes.', category: 'Linha' },
  { id: 'atk24', name: 'Garçom sem Gorjeta', icon: '🤵', description: 'Dá o passe e o companheiro erra.', category: 'Linha' },
  { id: 'atk25', name: 'Pé de Vento', icon: '🌪️', description: 'Corre mas a bola fica pra trás.', category: 'Linha' },

  // --- HABILIDADE: DEFESA ---
  { id: 'def1', name: 'Xerife do Bairro', icon: '👮', description: 'Aqui não passa nem vento, imagina atacante.', category: 'Linha' },
  { id: 'def2', name: 'Carrinho de Prata', icon: '🛷', description: 'Mestre do deserto de grama artificial.', category: 'Linha' },
  { id: 'def3', name: 'Muro de Berlim', icon: '🧱', description: 'Ninguém passa no 1 contra 1.', category: 'Linha' },
  { id: 'def4', name: 'Caneleiro de Elite', icon: '🪓', description: 'Bate com classe. O juiz nem vê.', category: 'Linha' },
  { id: 'def5', name: 'Lixeiro do Campo', icon: '🧹', description: 'Limpa todas as jogadas erradas do time.', category: 'Linha' },
  { id: 'def6', name: 'Antiaéreo', icon: '🚀', description: 'Tira todas de cabeça.', category: 'Linha' },
  { id: 'def7', name: 'Sombra do Atacante', icon: '👥', description: 'Marca tão perto que dá pra sentir o hálito.', category: 'Linha' },
  { id: 'def8', name: 'Bifão', icon: '🥩', description: 'Deu um chutão pra lua pra aliviar.', category: 'Linha' },
  { id: 'def9', name: 'Desarmador Atômico', icon: '⚛️', description: 'Tira a bola sem encostar no cara.', category: 'Linha' },
  { id: 'def10', name: 'Zagueiro Construtor', icon: '🏗️', description: 'Sabe sair jogando sem dar chutão.', category: 'Linha' },
  { id: 'def11', name: 'Cadeira Elétrica', icon: '⚡', description: 'O atacante que entra nela sai tremendo.', category: 'Linha' },
  { id: 'def12', name: 'Paredão Humano', icon: '🧱', description: 'Bloqueou 5 chutes no mesmo jogo.', category: 'Linha' },
  { id: 'def13', name: 'Ladrão de Sonhos', icon: '🕵️', description: 'Rouba a bola no último segundo.', category: 'Linha' },
  { id: 'def14', name: 'Caneleiro Poeta', icon: '📜', description: 'Dá rapa mas fala bonito pra não ser expulso.', category: 'Linha' },
  { id: 'def15', name: 'Sombra da Noite', icon: '🌃', description: 'Ninguém vê ele chegando pra desarmar.', category: 'Linha' },
  { id: 'def16', name: 'Xerife de Papel', icon: '🧻', description: 'Acha que marca mas é driblado fácil.', category: 'Linha' },
  { id: 'def17', name: 'Carrapato', icon: '🦟', description: 'Gruda no atacante e não larga mais.', category: 'Linha' },
  { id: 'def18', name: 'Espanta Bolas', icon: '💣', description: 'Só tira a bola com chutão pro alto.', category: 'Linha' },
  { id: 'def19', name: 'Mestre da Antecipação', icon: '🔮', description: 'Chega na bola antes do atacante pensar.', category: 'Linha' },
  { id: 'def20', name: 'Zagueiro Bailarino', icon: '💃', description: 'Tirou a bola com um giro de balé.', category: 'Linha' },

  // --- HABILIDADE: GOLEIRO ---
  { id: 'gl1', name: 'Paredão de Vantablack', icon: '🖤', description: 'Pegou até pensamento hoje.', category: 'Goleiro' },
  { id: 'gl2', name: 'Mão de Alface', icon: '🥬', description: 'Aceitou um frango histórico.', category: 'Goleiro' },
  { id: 'fr1', name: 'Frangueiro Profissional', icon: '🥚', description: 'O primeiro frango a gente nunca esquece.', category: 'Goleiro' },
  { id: 'fr5', name: 'Granja do Bueiro', icon: '🐣', description: '5 frangos confirmados. O time já nem confia mais.', category: 'Goleiro' },
  { id: 'gl3', name: 'Goleiro Voador', icon: '🦅', description: 'Se joga em todas as bolas, até nas fora.', category: 'Goleiro' },
  { id: 'gl4', name: 'Muralha do Crime', icon: '🚧', description: 'Incontestável. Fechou o bueiro.', category: 'Goleiro' },
  { id: 'gl5', name: 'Assustador de Atacante', icon: '👹', description: 'O cara fica com medo de chutar.', category: 'Goleiro' },
  { id: 'gl6', name: 'Lançador de Elite', icon: '🏹', description: 'Coloca o atacante na cara do gol com a mão.', category: 'Goleiro' },
  { id: 'gl7', name: 'Pegador de Pênalti', icon: '🛑', description: 'O pesadelo dos batedores.', category: 'Goleiro' },
  { id: 'gl8', name: 'Goleiro de Boné', icon: '🧢', description: 'Estilo puro, mas a bola passou por baixo.', category: 'Goleiro' },
  { id: 'gl9', name: 'Voz do Time', icon: '🗣️', description: 'Organiza a defesa aos gritos.', category: 'Goleiro' },
  { id: 'gl10', name: 'Elástico Humano', icon: '🤸', description: 'Defesas impossíveis de cinema.', category: 'Goleiro' },
  { id: 'gl11', name: 'Aranha Negra', icon: '🕷️', description: 'Parece ter 8 braços no gol.', category: 'Goleiro' },
  { id: 'gl12', name: 'Pé de Chumbo', icon: '⚓', description: 'Não pula, a gravidade venceu.', category: 'Goleiro' },
  { id: 'gl13', name: 'Grito de Guerra', icon: '📢', description: 'Acorda os vizinhos no grito com a zaga.', category: 'Goleiro' },
  { id: 'gl14', name: 'Mão de Ferro', icon: '✊', description: 'A bola bate e volta, mão duríssima.', category: 'Goleiro' },
  { id: 'gl15', name: 'Goleiro de Churrasco', icon: '🥩', description: 'Veio pro jogo mas tá pensando na carne.', category: 'Goleiro' },
  { id: 'gl16', name: 'Catador de Borboleta', icon: '🦋', description: 'Saiu mal no cruzamento.', category: 'Goleiro' },
  { id: 'gl17', name: 'Muralha de Isopor', icon: '🧊', description: 'Parece forte mas desmorona no primeiro chute.', category: 'Goleiro' },
  { id: 'gl18', name: 'Santo do Bueiro', icon: '😇', description: 'Fez uma defesa milagrosa no último minuto.', category: 'Goleiro' },
  { id: 'gl13', name: 'Handebol', icon: '🤾', description: 'Só defende com o pé, esquece a mão.', category: 'Goleiro' },
  { id: 'gl20', name: 'Goleiro Pipoca', icon: '🍿', description: 'Pula muito mas não pega nada.', category: 'Goleiro' },

  // --- BAGRE & VERGONHA (VITIMAS) ---
  { id: 'bg1', name: 'Bagre de Platina', icon: '🐟', description: 'Atingiu um nível de ruindade sobre-humano.', category: 'Geral' },
  { id: 'vt_cn1', name: 'Passarela de Caneta', icon: '🦵', description: 'Tomou a primeira caneta oficial. Fecha as perna!', category: 'Geral' },
  { id: 'vt_cn5', name: 'Túnel do Metrô', icon: '🚇', description: 'Tomou 5 canetas. Já virou atração turística do bueiro.', category: 'Geral' },
  { id: 'vt_ch1', name: 'Olhou pro Céu', icon: '🪁', description: 'Levou um chapéu e ficou procurando a bola.', category: 'Geral' },
  { id: 'vt_db1', name: 'No Chão', icon: '📉', description: 'Foi driblado e ficou sentado no gramado.', category: 'Geral' },
  { id: 'bg2', name: 'Inimigo da Bola', icon: '🚫', description: 'A bola foge dele como se fosse o diabo.', category: 'Geral' },
  { id: 'bg3', name: 'Tijoleiro', icon: '🧱', description: 'Domina a bola e ela vai pra 2 metros.', category: 'Geral' },
  { id: 'bg4', name: 'Cego de Várzea', icon: '🕶️', description: 'Não viu o companheiro livre do lado.', category: 'Geral' },
  { id: 'bg5', name: 'Perna de Grilo', icon: '🦗', description: 'Não tem força nem pra dar um passe.', category: 'Geral' },
  { id: 'bg6', name: 'Troféu Amigo do Adversário', icon: '🤝', description: 'Deu 3 assistências... pro outro time.', category: 'Geral' },
  { id: 'bg7', name: 'Chuteira de Ouro Invertida', icon: '💩', description: 'Errou 10 gols em uma semana.', category: 'Geral' },
  { id: 'bg8', name: 'Cone de Luxo', icon: '🚧', description: 'Só fica parado olhando o jogo passar.', category: 'Geral' },
  { id: 'bg9', name: 'Dorminhoco', icon: '😴', description: 'Ficou assistindo o contra-ataque acontecer.', category: 'Geral' },
  { id: 'bg10', name: 'O Pior que Já Vi', icon: '🤢', description: 'O ADM chorou vendo ele jogar.', category: 'Geral' },
  { id: 'bg11', name: 'Bagre Atômico', icon: '🧨', description: 'Consegue errar coisas fisicamente impossíveis.', category: 'Geral' },
  { id: 'bg12', name: 'Peixe Fora d\'Água', icon: '🐟', description: 'Parece que esqueceu como corre.', category: 'Geral' },
  { id: 'bg13', name: 'Chuteira de Chumbo', icon: '👞', description: 'Lento demais para o futebol moderno.', category: 'Geral' },
  { id: 'bg14', name: 'Inimigo da Lateral', icon: '↔️', description: 'Consegue cobrar lateral pro adversário.', category: 'Geral' },
  { id: 'bg15', name: 'Tonto Profissional', icon: '😵', description: 'Ficou tonto com o drible do adversário.', category: 'Geral' },
  { id: 'bg16', name: 'Bagre com Grife', icon: '🏷️', description: 'Usa chuteira de 1k mas joga igual um sapato.', category: 'Geral' },
  { id: 'bg17', name: 'Estátua de Sal', icon: '🧂', description: 'Ficou olhando a bola entrar no gol.', category: 'Geral' },
  { id: 'bg18', name: 'Pé de Pantufa de Ouro', icon: '🧸', description: 'Errou 5 chutes fracos no mesmo jogo.', category: 'Geral' },
  { id: 'bg19', name: 'Vítima da Gravidade', icon: '📉', description: 'Caiu sozinho drublando.', category: 'Geral' },
  { id: 'bg20', name: 'Rei do Quase', icon: '🤏', description: 'Quase fez gol, quase desarmou, quase jogou.', category: 'Geral' },

  // --- RESENHA & SOCIAL ---
  { id: 'rs1', name: 'Rádio Pelada', icon: '📻', description: 'Sabe da vida de todo mundo do grupo.', category: 'Geral' },
  { id: 'rs2', name: 'Mestre da Ironia', icon: '😏', description: 'Zoou o bagre com classe.', category: 'Geral' },
  { id: 'rs3', name: 'Organizador Fantasma', icon: '👻', description: 'Ajuda mas nunca aparece na foto.', category: 'Geral' },
  { id: 'rs4', name: 'Fiscal de Mensalidade', icon: '🧐', description: 'Sabe quem não pagou antes do ADM.', category: 'Geral' },
  { id: 'rs5', name: 'Guru da Várzea', icon: '🧘', description: 'Dá conselhos sobre a vida depois do jogo.', category: 'Geral' },
  { id: 'rs6', name: 'Piadista Sem Graça', icon: '🤡', description: 'Conta piada no meio da briga.', category: 'Geral' },
  { id: 'rs7', name: 'Rei do Stickers', icon: '🖼️', description: 'Só fala por figurinhas no Zap.', category: 'Geral' },
  { id: 'rs8', name: 'Inimigo do Silêncio', icon: '🔊', description: 'Não para de falar nem quando tá jogando.', category: 'Geral' },
  { id: 'rs9', name: 'Pacificador', icon: '🕊️', description: 'Separou 5 brigas no mesmo mês.', category: 'Geral' },
  { id: 'rs10', name: 'O Cara da Geladeira', icon: '🧊', description: 'Sempre traz o gelo pro pós-jogo.', category: 'Geral' },

  // --- MANIAS & QUIRKS ---
  { id: 'mn1', name: 'Cheira-Fim-de-Jogo', icon: '👃', description: 'Sempre pergunta "falta quanto?" desde os 5 min.', category: 'Geral' },
  { id: 'mn2', name: 'O Cara do Spray', icon: '💨', description: 'Passa gelol até no cabelo se deixar.', category: 'Geral' },
  { id: 'mn3', name: 'Amigo do Gandula', icon: '🎾', description: 'Ajuda a buscar a bola 10 vezes.', category: 'Geral' },
  { id: 'mn4', name: 'Critico de Chuteira', icon: '👟', description: 'Sabe o modelo da chuteira de todo mundo.', category: 'Geral' },
  { id: 'mn5', name: 'Mestre da Atadura', icon: '🩹', description: 'Enrola 2km de atadura no tornozelo.', category: 'Geral' },
  { id: 'mn6', name: 'Cansado Profissional', icon: '😫', description: 'Pede substituição com 2 min de jogo.', category: 'Geral' },
  { id: 'mn7', name: 'Rei do Arremesso', icon: '👐', description: 'Cobrou 5 laterais perfeitos no peito do time.', category: 'Geral' },
  { id: 'mn8', name: 'Escapista', icon: '🏃', description: 'Sempre foge da hora de recolher os coletes.', category: 'Geral' },
  { id: 'mn9', name: 'O Cara da Garrafinha', icon: '🍼', description: 'Tem a garrafa mais estilosa (e vazia).', category: 'Geral' },
  { id: 'mn10', name: 'Mestre da Lamentação', icon: '🤦', description: 'Errou o passe e deu um soco no chão.', category: 'Geral' },

  // --- TIERS DE CONQUISTA ---
  { id: 'brz1', name: 'Iniciante do Bronze', icon: '🥉', description: 'Fez 1 gol na temporada.', category: 'Elite' },
  { id: 'brz2', name: 'Passador de Bronze', icon: '🥉', description: 'Deu 1 assistência na temporada.', category: 'Elite' },
  { id: 'brz3', name: 'Zagueiro de Bronze', icon: '🥉', description: 'Ganhou 1 jogo na zaga.', category: 'Elite' },
  { id: 'brz4', name: 'Goleiro de Bronze', icon: '🥉', description: 'Fez 1 defesa difícil.', category: 'Elite' },
  { id: 'brz5', name: 'Bronzeado', icon: '🥉', description: 'Participou de 3 peladas seguidas.', category: 'Elite' },
  { id: 'sil1', name: 'Artilheiro de Prata', icon: '🥈', description: 'Fez 10 gols na temporada.', category: 'Elite' },
  { id: 'sil2', name: 'Garçom de Prata', icon: '🥈', description: 'Deu 5 assistências na temporada.', category: 'Elite' },
  { id: 'sil3', name: 'Muralha de Prata', icon: '🥈', description: 'Invicto por 3 jogos seguidos.', category: 'Elite' },
  { id: 'gol1', name: 'Lenda de Ouro', icon: '🥇', description: 'O melhor jogador do mês.', category: 'Elite' },
  { id: 'gol2', name: 'Chuteira de Ouro', icon: '🥇', description: 'Artilheiro absoluto da temporada.', category: 'Elite' },
  { id: 'gol3', name: 'Luva de Ouro', icon: '🥇', description: 'Goleiro menos vazado.', category: 'Elite' },

  // --- QUANTITATIVOS & PROGRESSÃO ---
  { id: 'g1a', name: 'Gofre 1', icon: '⚽', description: 'Primeiro gol marcado.', category: 'Linha' },
  { id: 'g10', name: 'Gofre 10', icon: '🔟', description: '10 gols marcados na história.', category: 'Linha' },
  { id: 'g50', name: 'Gofre 50', icon: '🎖️', description: '50 gols marcados. Artilheiro nato.', category: 'Linha' },
  { id: 'g100', name: 'Gofre 100', icon: '👑', description: 'CENTENÁRIO DO BUEIRO.', category: 'Linha' },
  { id: 'a1', name: 'Garçom 1', icon: '🍷', description: 'Primeira assistência.', category: 'Linha' },
  { id: 'a10', name: 'Garçom 10', icon: '🍷', description: '10 assistências na história.', category: 'Linha' },
  { id: 'a50', name: 'Garçom 50', icon: '🍷', description: '50 assistências. Visão de águia.', category: 'Linha' },

  // --- ESPECIAIS & VANTABLACK ---
  { id: 'vb1', name: 'Essência de Vantablack', icon: '🌑', description: 'Entendeu o espírito da ruindade.', category: 'Architect' },
  { id: 'vb2', name: 'Sombra do Bueiro', icon: '👤', description: 'Vê tudo, ouve tudo, joga nada.', category: 'Architect' },
  { id: 'vb3', name: 'Cavaleiro das Trevas', icon: '🦇', description: 'Joga melhor sob pressão e xingamentos.', category: 'Architect' },
  { id: 'st1', name: 'Gol de Placa', icon: '🏙️', description: 'Fez um gol que merecia placa no bueiro.', category: 'Linha' },
  { id: 'st2', name: 'Defesa do Século', icon: '🧤', description: 'Pegou uma bola que já tava dentro.', category: 'Goleiro' },

  // --- LEGADO & AUTORIDADE (TOP TIER) ---
  { id: 'leg1', name: 'Fundador da Pelada', icon: '👑', description: 'O patriarca que começou tudo isso aqui. Respeite o ancião.', category: 'Elite' },
  { id: 'leg2', name: 'Administrador da Biqueira', icon: '👮‍♂️', description: 'Quem manda nessa porra. A palavra final é dele.', category: 'Elite' },
  { id: 'leg3', name: 'Bola de Ouro Suprema', icon: '🥇', description: 'O ápice da excelência técnica e moral. O melhor dos melhores.', category: 'Elite' },
  { id: 'leg4', name: 'Sócio Vitalício', icon: '🎟️', description: 'Parte inseparável da história desse bueiro.', category: 'Elite' },
  { id: 'leg5', name: 'Embaixador da Várzea', icon: '🌍', description: 'Leva o nome do FDP por onde passa.', category: 'Elite' },

  // --- MAGIA & TÉCNICA (GOOD BADGES) ---
  { id: 'mg1', name: 'Rabiscador', icon: '🖌️', description: 'Desenha a jogada no chão. Arte pura.', category: 'Linha' },
  { id: 'mg2', name: 'Driblador Nato', icon: '🐍', description: 'A bola parece uma extensão do corpo dele.', category: 'Linha' },
  { id: 'mg3', name: 'Maestro', icon: '🎼', description: 'O cérebro do time. Rege o jogo com calma e visão.', category: 'Linha' },
  { id: 'mg4', name: 'Goleiro-Linha Decisivo', icon: '🧤⚽', description: 'Saiu do gol pra decidir no ataque. Fenômeno.', category: 'Goleiro' },
  { id: 'mg5', name: 'Pé de Veludo', icon: '🩰', description: 'Domínio impecável. A bola dorme no pé.', category: 'Linha' },
  { id: 'mg6', name: 'Visão de Águia', icon: '🦅', description: 'Enxerga o passe em profundidade antes de todo mundo.', category: 'Linha' },
  { id: 'mg7', name: 'Estrategista', icon: '♟️', description: 'Sabe se posicionar e ditar o ritmo da partida.', category: 'Linha' },
  { id: 'mg8', name: 'Garçom com Estrela', icon: '⭐', description: 'Assistências que valem mais que gols.', category: 'Linha' },
  { id: 'mg9', name: 'Elástico de Ouro', icon: '🪀', description: 'Mestre do drible do Ronaldinho.', category: 'Linha' },
  { id: 'mg10', name: 'Finta Mortal', icon: '💀', description: 'Desloca o marcador sem nem encostar na bola.', category: 'Linha' },

  // --- RAÇA & LUTA ---
  { id: 'rc1', name: 'Coração de Leão', icon: '🦁', description: 'Não desiste de nenhuma bola, até a última gota de suor.', category: 'Geral' },
  { id: 'rc2', name: 'Pulmão de Aço', icon: '🌬️', description: 'Corre o jogo todo sem pedir substituição.', category: 'Geral' },
  { id: 'rc3', name: 'Carrasco do Meio-Campo', icon: '⚓', description: 'Domina o setor central com força e autoridade.', category: 'Linha' },
  { id: 'rc4', name: 'Zagueiro Imortal', icon: '🛡️', description: 'Leva bolada, leva pancada e continua de pé.', category: 'Linha' },
  { id: 'rc5', name: 'Guerreiro Vantablack', icon: '🌑', description: 'Sua presença intimida o adversário pela raça.', category: 'Elite' },
  { id: 'rc6', name: 'Inimigo da Derrota', icon: '😤', description: 'Joga com sangue nos olhos até o apito final.', category: 'Geral' },
  { id: 'rc7', name: 'Escudo Humano', icon: '🧱', description: 'Se joga na frente dos chutes pra salvar o goleiro.', category: 'Linha' },
  { id: 'rc8', name: 'Motorista do Meio', icon: '⚙️', description: 'Faz o time andar. A engrenagem perfeita.', category: 'Linha' },
  { id: 'rc9', name: 'Tanque de Guerra', icon: '🚜', description: 'Ninguém tira ele no ombro. Inabalável.', category: 'Linha' },
  { id: 'rc10', name: 'Interceptador X', icon: '📡', description: 'Lê as linhas de passe e corta tudo.', category: 'Linha' },

  // --- DEFINIÇÃO & GOL ---
  { id: 'gl1a', name: 'Finalizador de Elite', icon: '🎯', description: 'Chute seco, rasteiro e no canto. Indefensável.', category: 'Linha' },
  { id: 'gl1b', name: 'Sniper da Várzea', icon: '🏹', description: 'Coloca a bola no ângulo com precisão suíça.', category: 'Linha' },
  { id: 'gl1c', name: 'Carrasco de Goleiros', icon: '🩸', description: 'O pesadelo número 1 de quem veste luvas.', category: 'Linha' },
  { id: 'gl1d', name: 'Artilheiro Iluminado', icon: '✨', description: 'Sempre no lugar certo pra empurrar pro fundo da rede.', category: 'Linha' },
  { id: 'gl1e', name: 'Bicicleta Perfeita', icon: '🚲', description: 'Acertou o movimento lendário com perfeição.', category: 'Linha' },
  { id: 'gl1f', name: 'Mestre do Sem-Pulo', icon: '👟', description: 'Pega de primeira e fura a rede.', category: 'Linha' },
  { id: 'gl1g', name: 'Cabeceador de Ouro', icon: '📀', description: 'Imbatível no jogo aéreo ofensivo.', category: 'Linha' },
  { id: 'gl1h', name: 'Rei do Rebote', icon: '🦊', description: 'Oportunista nato. Não perdoa erro da defesa.', category: 'Linha' },
  { id: 'gl1i', name: 'Canhão da Biqueira', icon: '💥', description: 'Chute potente que assusta até o juiz.', category: 'Linha' },
  { id: 'gl1j', name: 'Matador Frio', icon: '🧊', description: 'Na cara do gol, ele nunca treme.', category: 'Linha' },

  // --- LIDERANÇA & SOCIAL ---
  { id: 'ld1', name: 'Capitão de Alma', icon: '👨‍✈️', description: 'Lidera pelo exemplo e pela voz positiva.', category: 'Elite' },
  { id: 'ld2', name: 'Espírito de Grupo', icon: '🤝', description: 'Sempre coloca o time acima de si mesmo.', category: 'Geral' },
  { id: 'ld3', name: 'Fair Play de Elite', icon: '🕊️', description: 'Joga duro, mas com uma honestidade exemplar.', category: 'Geral' },
  { id: 'ld4', name: 'Motivador Nato', icon: '🔥', description: 'Levanta o moral do time quando as coisas estão ruins.', category: 'Geral' },
  { id: 'ld5', name: 'Diplomata do Bueiro', icon: '🤝', description: 'Resolve tretas e mantém a paz na resenha.', category: 'Geral' },

  // --- HABILIDADES ESPECÍFICAS ---
  { id: 'sk1', name: 'Pivô Inteligente', icon: '🏗️', description: 'Usa o corpo pra criar espaços pros companheiros.', category: 'Linha' },
  { id: 'sk2', name: 'Passador Milimétrico', icon: '📏', description: 'Passes de 30 metros que caem no pé.', category: 'Linha' },
  { id: 'sk3', name: 'Lançador de Elite', icon: '🛰️', description: 'Inicia o contra-ataque com precisão de mísseis.', category: 'Linha' },
  { id: 'sk4', name: 'Dono da Latera', icon: '🏃‍♂️💨', description: 'Domina o corredor lateral com velocidade e técnica.', category: 'Linha' },
  { id: 'sk5', name: 'Mestre da Cobertura', icon: '☂️', description: 'Sempre salvando o erro do companheiro na defesa.', category: 'Linha' },
  { id: 'sk6', name: 'Goleiro Elástico', icon: '🤸', description: 'Defesas plásticas que fazem a galera aplaudir.', category: 'Goleiro' },
  { id: 'sk7', name: 'Muralha Mental', icon: '🧠', description: 'Não se abala com pressão nem com torcida contra.', category: 'Geral' },
  { id: 'sk8', name: 'Rei da Antecipação', icon: '🔮', description: 'Parece prever onde a bola vai estar.', category: 'Linha' },
  { id: 'sk9', name: 'Dono do Escanteio', icon: '🚩', description: 'Cobranças venenosas que resultam em gol.', category: 'Linha' },
  { id: 'sk10', name: 'Meia de Ligação', icon: '🔗', description: 'A ponte perfeita entre a defesa e o ataque.', category: 'Linha' },

  // --- CONQUISTAS DE ÉPOCA ---
  { id: 'ep1', name: 'Invicto do Mês', icon: '🛡️', description: 'Nenhuma derrota registrada em 30 dias.', category: 'Elite' },
  { id: 'ep2', name: 'Campeão da Rodada', icon: '🏆', description: 'Destaque absoluto em uma pelada específica.', category: 'Elite' },
  { id: 'ep3', name: 'MVP do Trimestre', icon: '⭐', description: 'Consistência máxima durante 3 meses.', category: 'Elite' },
  { id: 'ep4', name: 'Hattrick Heróico', icon: '⚽⚽⚽', description: '3 gols em um jogo onde o time estava perdendo.', category: 'Linha' },
  { id: 'ep5', name: 'Virada Épica', icon: '🔄', description: 'Liderou o time em uma virada histórica.', category: 'Geral' },

  // --- ATRIBUTOS VANTABLACK ---
  { id: 'vb4', name: 'Sombra Silenciosa', icon: '👤', description: 'Ninguém nota, mas ele decidiu o jogo nos detalhes.', category: 'Architect' },
  { id: 'vb5', name: 'Terror dos Bagres', icon: '😱', description: 'Sua presença faz o adversário errar o domínio.', category: 'Architect' },
  { id: 'vb6', name: 'Elegância Noir', icon: '🕺', description: 'Joga um futebol bonito e minimalista.', category: 'Architect' },
  { id: 'vb7', name: 'Arquiteto do Jogo', icon: '📐', description: 'Desenha a vitória passo a passo.', category: 'Architect' },

  // --- BADGES DE IMPACTO ---
  { id: 'im1', name: 'Substituto de Ouro', icon: '♻️', description: 'Entrou no segundo tempo e mudou o jogo.', category: 'Geral' },
  { id: 'im2', name: 'Coringa do Bueiro', icon: '🃏', description: 'Joga bem em qualquer posição que o ADM colocar.', category: 'Geral' },
  { id: 'im3', name: 'Inimigo do Empate', icon: '🚫🤝', description: 'Sempre busca a vitória, custe o que custar.', category: 'Geral' },
  { id: 'im4', name: 'Garra de Diamante', icon: '💎', description: 'Mesmo cansado, sua técnica não cai.', category: 'Elite' },
  { id: 'im5', name: 'Clarão na Escuridão', icon: '💡', description: 'Num jogo ruim, ele foi o ponto de luz técnica.', category: 'Elite' },

  // --- TACTICAL MASTERY ---
  { id: 'ta1', name: 'Professor da Zaga', icon: '🎓', description: 'Dá aula de como marcar sem fazer falta.', category: 'Linha' },
  { id: 'ta2', name: 'Cão de Guarda', icon: '🐕', description: 'Não larga o pé do melhor jogador deles.', category: 'Linha' },
  { id: 'ta3', name: 'Postura de Craque', icon: '🕴️', description: 'Joga de cabeça erguida, com classe total.', category: 'Elite' },
  { id: 'ta4', name: 'Mestre da Transição', icon: '⚡', description: 'Transforma defesa em ataque num piscar de olhos.', category: 'Linha' },
  { id: 'ta5', name: 'Bloqueio Mental', icon: '🧱', description: 'Anulou o principal articulador adversário.', category: 'Linha' },

  // --- MAGICAL TOUCH ---
  { id: 'mgg11', name: 'Caneta de Vidro', icon: '🪄', description: 'Caneta tão fina que o cara nem sentiu.', category: 'Linha' },
  { id: 'mgg12', name: 'Chapéu Amestrado', icon: '🐦', description: 'A bola parece que obedece a mente dele.', category: 'Linha' },
  { id: 'mgg13', name: 'Passe de Letra', icon: '🤴', description: 'Elegância máxima na hora de servir.', category: 'Linha' },
  { id: 'mgg14', name: 'Gol de Calcanhar', icon: '👣', description: 'Finalização inesperada e genial.', category: 'Linha' },
  { id: 'mgg15', name: 'Domínio Negativo', icon: '📉', description: 'Mata a bola e o momentum do adversário ao mesmo tempo.', category: 'Linha' },

  // --- PROGRESSIVE POSITIVE ---
  { id: 'ppp1', name: 'Promessa da Base', icon: '🌱', description: 'Mostrando evolução clara a cada pelada.', category: 'Geral' },
  { id: 'ppp2', name: 'Revelação do Ano', icon: '🌟', description: 'Chegou agora e já é indispensável.', category: 'Elite' },
  { id: 'ppp3', name: 'Consistência Pura', icon: '📈', description: 'Mantém o nível alto por 10 jogos consecutivos.', category: 'Elite' },
  { id: 'ppp4', name: 'Pilar do Time', icon: '🏛️', description: 'A base onde a vitória é construída.', category: 'Geral' },
  { id: 'ppp5', name: 'Lendário no Bueiro', icon: '🔥', description: 'Seu nome será lembrado por gerações de pernas de pau.', category: 'Elite' },

  // --- SOCIAL & RESENHA POSITIVA ---
  { id: 'spp1', name: 'Cervejeiro de Honra', icon: '🍻', description: 'Traz a gelada e a alegria pro pós-jogo.', category: 'Geral' },
  { id: 'spp2', name: 'Alma da Biqueira', icon: '🎭', description: 'Essencial pra resenha ser boa.', category: 'Geral' },
  { id: 'spp3', name: 'Conselheiro da Várzea', icon: '👴', description: 'Sempre tem uma palavra sobre o jogo e a vida.', category: 'Geral' },
  { id: 'spp4', name: 'Fotógrafo Oficial', icon: '📸', description: 'Garante que os feitos sejam registrados.', category: 'Geral' },
  { id: 'spp5', name: 'Rei do Churrasco Especial', icon: '🔥🥩', description: 'Garante a proteína da nossa sobrevivência.', category: 'Geral' },

  // --- REFORÇO EXTRA PARA CHEGAR A 100+ ---
  { id: 'exx1', name: 'Gatuno de Bolas', icon: '🥷', description: 'Rouba a bola e some nas sombras.', category: 'Linha' },
  { id: 'exx2', name: 'Zagueiro Artilheiro Supremo', icon: '🛡️⚽', description: 'Lá atrás ele resolve, lá na frente ele decide.', category: 'Linha' },
  { id: 'exx3', name: 'Muralha de Vantablack III', icon: '🧱', description: 'Reforço defensivo imparável.', category: 'Linha' },
  { id: 'exx4', name: 'Articulador de Elite', icon: '👨‍🦲', description: 'Controla o jogo como se fosse videogame.', category: 'Linha' },
  { id: 'exx5', name: 'Sprint Imortal', icon: '🏃‍♂️💨', description: 'Velocidade máxima mesmo aos 90 min.', category: 'Linha' },
  { id: 'exx6', name: 'Pé de Ferro de Ouro', icon: '👞✨', description: 'Ganha todas as divididas.', category: 'Linha' },
  { id: 'exx7', name: 'Cão de Guarda de Elite', icon: '🚔', description: 'O vigilante supremo da zaga.', category: 'Linha' },
  { id: 'exx8', name: 'Matador Silencioso de Ouro', icon: '🤫', description: 'Não fala nada, mas faz 5 gols.', category: 'Linha' },
  { id: 'exx9', name: 'Ala Moderno Supersônico', icon: '✈️', description: 'Faz o vaivém com perfeição tática.', category: 'Linha' },
  { id: 'exx10', name: 'Lenda Urbana Infinita', icon: '🏙️', description: 'Aruína dos adversários, glória dos aliados.', category: 'Elite' },
  { id: 'exx11', name: 'Finta de Corpo Genial', icon: '🕺', description: 'Dribla sem tocar na bola.', category: 'Linha' },
  { id: 'exx12', name: 'Controle de Grupo Supremo', icon: '📣', description: 'Sabe acalmar os ânimos exaltados.', category: 'Geral' },
  { id: 'exx13', name: 'Passe de Trivela Magistral', icon: '🌀', description: 'Estilo Quaresma no bueiro.', category: 'Linha' },
  { id: 'exx14', name: 'Amigo do ADM de Luxo', icon: '🍹', description: 'Tem privilégios reais na biqueira.', category: 'Geral' },
  { id: 'exx15', name: 'Infiltrado de Elite Invisível', icon: '👻', description: 'Sempre aparece livre na área.', category: 'Linha' },
  { id: 'exx16', name: 'Goleiro Líbero de Ouro', icon: '🏃‍♂️🧤', description: 'Joga com os pés melhor que muito atacante.', category: 'Goleiro' },
  { id: 'exx17', name: 'Resiliência Imortal', icon: '🧘‍♀️', description: 'Errou o gol mas fez o próximo decisivo.', category: 'Geral' },
  { id: 'exx18', name: 'Visão de Jogo Infinita', icon: '🔄', description: 'Sabe onde todos estão em campo.', category: 'Linha' },
  { id: 'exx19', name: 'Cavalheiro de Honra', icon: '🎩✨', description: 'Educado até pra dar o rapa.', category: 'Geral' },
  { id: 'exx20', name: 'Símbolo da Pelada Eterno', icon: '🏷️', description: 'A cara oficial do nosso grupo.', category: 'Elite' },
  { id: 'exx21', name: 'Mestre do drible da vaca Supremo', icon: '🐄💨', description: 'Finta o adversário e busca do outro lado.', category: 'Linha' },
  { id: 'exx22', name: 'Goleiro de Handebol v3', icon: '🤾‍♂️🔥', description: 'Defesa com os pés digna de olimpíadas.', category: 'Goleiro' },
  { id: 'exx23', name: 'Cruzamento de Ouro Puro', icon: '🥐✨', description: 'Bola na medida pro atacante guardar.', category: 'Linha' },
  { id: 'exx24', name: 'Desarmador de Elite Relâmpago', icon: '🛠️⚡', description: 'Desmontou o ataque adversário sozinho.', category: 'Linha' },
  { id: 'exx25', name: 'Cérebro do Time Vantablack', icon: '🧠🌑', description: 'Pensa o jogo 3 jogadas à frente.', category: 'Linha' },
  { id: 'exx26', name: 'Garra do Bueiro', icon: '🥊', description: 'Luta por cada centímetro de campo.', category: 'Geral' },
  { id: 'exx27', name: 'Finalização de Placa', icon: '🏙️', description: 'Cada chute é uma pintura.', category: 'Linha' },
  { id: 'exx28', name: 'Maestro do Meio-Campo', icon: '🧶', description: 'Tece o jogo com fios de ouro.', category: 'Linha' },
  { id: 'exx29', name: 'Inimigo do Bagre', icon: '👿', description: 'Sua qualidade técnica anula a ruindade alheia.', category: 'Linha' },
  { id: 'exx30', name: 'Patrimônio da Noite', icon: '🌙', description: 'O rei das peladas noturnas.', category: 'Elite' },

  // --- EXTRA EXPERIENCE UNIVERSE ---
  { id: 'gx1', name: 'Dono do Meio', icon: '🕹️', description: 'Controla a meiuca com sabedoria.', category: 'Linha' },
  { id: 'gx2', name: 'Marcação de Ouro', icon: '🛡️', description: 'Não deixa o craque deles respirar.', category: 'Linha' },
  { id: 'gx3', name: 'Pivô de Vidro', icon: '🏗️', description: 'Faz a parede e serve com açúcar.', category: 'Linha' },
  { id: 'gx4', name: 'Ala de Ferro', icon: '🏃‍♂️', description: 'Cobre o corredor com raça absoluta.', category: 'Linha' },
  { id: 'gx5', name: 'Artilheiro do Povo', icon: '🏟️', description: 'Sempre faz o gol da vitória da galera.', category: 'Linha' },
  { id: 'gx6', name: 'Guerreador do Bueiro', icon: '🛡️', description: 'Não tem medo de cara feia nem dividida.', category: 'Geral' },
  { id: 'gx7', name: 'Passador de Elite', icon: '📏', description: 'Acha o companheiro livre até no escuro.', category: 'Linha' },
  { id: 'gx8', name: 'Mestre da Retomada', icon: '🔄', description: 'Perde a bola e recupera no mesmo segundo.', category: 'Linha' },
  { id: 'gx9', name: 'Lumina da Biqueira', icon: '✨', description: 'Sua sorte contagia o time inteiro.', category: 'Elite' },
  { id: 'gx10', name: 'Inabalável', icon: '🗿', description: 'Pode estar perdendo de 10, ele continua jogando sério.', category: 'Geral' },
  { id: 'gx11', name: 'Visão Futurista', icon: '🔮', description: 'Sabe onde a bola vai sobrar antes dela espirrar.', category: 'Linha' },
  { id: 'gx12', name: 'Espírito Inquebrável', icon: '🎗️', description: 'Liderança positiva em momentos críticos.', category: 'Geral' },
  { id: 'gx13', name: 'Mãos de Ouro (Goleiro)', icon: '🧤✨', description: 'Pega até pensamento.', category: 'Goleiro' },
  { id: 'gx14', name: 'Salto Ornamental', icon: '🤸‍♂️', description: 'Defesa de cinema que salvou o resultado.', category: 'Goleiro' },
  { id: 'gx15', name: 'Comandante da Zaga', icon: '🗣️🛡️', description: 'Organiza a defesa com autoridade.', category: 'Linha' },
  { id: 'gx16', name: 'Coringa Decisivo', icon: '🃏', description: 'Aparece em qualquer lugar pra matar o jogo.', category: 'Linha' },
  { id: 'gx17', name: 'Sombra Imparável', icon: '👤', description: 'Ninguém marca ele, pois ninguém o vê chegando.', category: 'Linha' },
  { id: 'gx18', name: 'Pé de Anjo', icon: '👼', description: 'Finalizações com uma curva impossível.', category: 'Linha' },
  { id: 'gx19', name: 'Escultor de Jogadas', icon: '🔨', description: 'Constrói a vitória com paciência.', category: 'Linha' },
  { id: 'gx20', name: 'Relíquia do FDP', icon: '🏺', description: 'Um jogador raro, técnico e leal.', category: 'Elite' },

  // --- EXTRA GENERATION (PARA GARANTIR 300+) ---
  // --- O LAGO DOS BAGRES (70+ NEW BADGES) ---
  { id: 'bg_v1', name: 'Bagre de Pantufa', icon: '🦶', description: 'Corre mas não faz barulho. Nem aparece no jogo.', category: 'Bagre' },
  { id: 'bg_v2', name: 'Inimigo do Gol', icon: '🚫⚽', description: 'Se a bola fosse uma bomba, ele estaria vivo. Foge do gol.', category: 'Bagre' },
  { id: 'bg_v3', name: 'Chuteira de Cristal Quebrado', icon: '🔨', description: 'Dá um chute e já pede pra sair com cãibra.', category: 'Bagre' },
  { id: 'bg_v4', name: 'Pé de Alface Atômico', icon: '🥬', description: 'Domina a bola e ela volta pro meio de campo.', category: 'Bagre' },
  { id: 'bg_v5', name: 'Cego de Várzea Profissional', icon: '🕶️', description: 'O companheiro tá livre na cara do gol, ele chuta pro mato.', category: 'Bagre' },
  { id: 'bg_v6', name: 'Carregador de Piano Quebrado', icon: '🎹', description: 'Tenta ajudar mas só atrapalha a subida do time.', category: 'Bagre' },
  { id: 'bg_v7', name: 'Zagueiro de Papelão', icon: '📦', description: 'Qualquer drible simples ele desmonta.', category: 'Bagre' },
  { id: 'bg_v8', name: 'Goleiro de Boné Furado', icon: '🧢', description: 'Pula pra foto, mas a bola já tinha entrado.', category: 'Bagre' },
  { id: 'bg_v9', name: 'Atacante de Vidro', icon: '🍷', description: 'Finalização tão frágil que o goleiro pega com o pé.', category: 'Bagre' },
  { id: 'bg_v10', name: 'Bifão Queimado', icon: '🥩', description: 'Aquele chutão pra tirar que cai no pé do centroavante deles.', category: 'Bagre' },
  { id: 'bg_v11', name: 'Âncora de Isopor', icon: '⚓', description: 'Parece que vai segurar o time, mas flutua pra longe.', category: 'Bagre' },
  { id: 'bg_v12', name: 'Sombra do Próprio Medo', icon: '👤', description: 'Fica escondido atrás do marcador pra não receber a bola.', category: 'Bagre' },
  { id: 'bg_v13', name: 'Caneleiro Poeta Triste', icon: '📜', description: 'Dá o rapa e ainda pede desculpa chorando.', category: 'Bagre' },
  { id: 'bg_v14', name: 'Rei do Passe Lateral Infinito', icon: '↔️', description: 'Não avança 1 metro. Só toca pro lado e pra trás.', category: 'Bagre' },
  { id: 'bg_v15', name: 'Driblador de Vento', icon: '🌪️', description: 'Faz o drible, a bola fica, e ele vai sozinho.', category: 'Bagre' },
  { id: 'bg_v16', name: 'O Pior que a NASA já viu', icon: '🔭', description: 'Erros que desafiam as leis da física moderna.', category: 'Bagre' },
  { id: 'bg_v17', name: 'Vítima da Gravidade Exagerada', icon: '📉', description: 'Cai 10 vezes por jogo sem ninguém encostar.', category: 'Bagre' },
  { id: 'bg_v18', name: 'Reserva do Reserva', icon: '🛋️', description: 'Só entra se o juiz também cansar.', category: 'Bagre' },
  { id: 'bg_v19', name: 'Escultor de Frangos', icon: '🥚', description: 'Cada defesa é uma obra de arte do erro.', category: 'Bagre' },
  { id: 'bg_v20', name: 'Pé de Algodão Doce', icon: '☁️', description: 'Passe tão devagar que a grama para a bola.', category: 'Bagre' },
  { id: 'bg_v21', name: 'Atleta de Buffet', icon: '🍱', description: 'Só corre pra comer o churrasco depois do jogo.', category: 'Bagre' },
  { id: 'bg_v22', name: 'Zumbi da Lateral', icon: '🧟', description: 'Fica andando na linha sem saber o que tá acontecendo.', category: 'Bagre' },
  { id: 'bg_v23', name: 'Inimigo do Oxigênio', icon: '💨', description: 'Cansa na hora de bater o centro inicial.', category: 'Bagre' },
  { id: 'bg_v24', name: 'Vampiro de Sol', icon: '☀️', description: 'Não aguenta 5 min de jogo se tiver luz.', category: 'Bagre' },
  { id: 'bg_v25', name: 'Padeiro do Bueiro', icon: '🥐', description: 'Sempre entregando o "pão" pro adversário.', category: 'Bagre' },
  { id: 'bg_v26', name: 'Mestre da Furada', icon: '⛳', description: 'Tenta chutar e acerta o ar majestosamente.', category: 'Bagre' },
  { id: 'bg_v27', name: 'Teletransportado', icon: '✨', description: 'Sumiu do jogo por 20 minutos sem ninguém notar.', category: 'Bagre' },
  { id: 'bg_v28', name: 'Pé de Chumbo Inoxidável', icon: '⚓', description: 'Velocidade máxima de 2km/h.', category: 'Bagre' },
  { id: 'bg_v29', name: 'Chorão com Grife', icon: '😭', description: 'Reclama que a grama tá torta quando erra o chute.', category: 'Bagre' },
  { id: 'bg_v30', name: 'Mãos de Quiabo', icon: '🥒', description: 'A bola escorrega da mão em todo chute fácil.', category: 'Bagre' },
  { id: 'bg_v31', name: 'Pé de Valsa Desafinado', icon: '💃', description: 'Tenta driblar e acaba se enroscando na bola.', category: 'Bagre' },
  { id: 'bg_v32', name: 'Tijoleiro Master', icon: '🧱', description: 'Domínio de bola que quebra o piso do campo.', category: 'Bagre' },
  { id: 'bg_v33', name: 'Mestre do drible da vaca... reversa', icon: '🐄', description: 'A bola vai pra um lado, ele pro outro e o boi foge.', category: 'Bagre' },
  { id: 'bg_v34', name: 'Inimigo do Lançamento', icon: '🛰️', description: 'Tenta lançar e acerta o carro do vizinho.', category: 'Bagre' },
  { id: 'bg_v35', name: 'Escorregador Profissional', icon: '🧼', description: 'Usa a chuteira errada em todo jogo.', category: 'Bagre' },
  { id: 'bg_v36', name: 'Bagre com Diploma', icon: '🎓', description: 'Sabe a teoria do futebol, mas a prática é um desastre.', category: 'Bagre' },
  { id: 'bg_v37', name: 'Falso Atleta', icon: '🤡', description: 'Traje completo de craque, futebol de amador.', category: 'Bagre' },
  { id: 'bg_v38', name: 'Garçonete de Boteco', icon: '🍻', description: 'Só serve bola ruim pros companheiros.', category: 'Bagre' },
  { id: 'bg_v39', name: 'Zagueiro Pipoca de Microondas', icon: '🍿', description: 'Pula alto mas some no primeiro contato.', category: 'Bagre' },
  { id: 'bg_v40', name: 'Inimigo da Verticalidade', icon: '↔️', description: 'Sempre corta pra trás quando o gol tá livre.', category: 'Bagre' },
  { id: 'bg_v41', name: 'Pé de Pantufa Peluda', icon: '🧸', description: 'O chute mais fofo do bueiro.', category: 'Bagre' },
  { id: 'bg_v42', name: 'Olheiro de Gol', icon: '🧐', description: 'Só fica olhando a bola entrar sem se mexer.', category: 'Bagre' },
  { id: 'bg_v43', name: 'Mestre da Caneta Reversa', icon: '🖊️', description: 'Consegue tomar caneta até do juiz.', category: 'Bagre' },
  { id: 'bg_v44', name: 'Atleta de Slow Motion', icon: '🎞️', description: 'Parece que o jogo dele tá em 0.5x.', category: 'Bagre' },
  { id: 'bg_v45', name: 'Bifão Congelado', icon: '❄️', description: 'Chutão duro que nem sobe.', category: 'Bagre' },
  { id: 'bg_v46', name: 'Maestro de Desastres', icon: '🎼', description: 'Organiza o time pra levar contra-ataque.', category: 'Bagre' },
  { id: 'bg_v47', name: 'Perna de Pau de Carvalho', icon: '🪵', description: 'Elevou a ruindade a um nível botânico.', category: 'Bagre' },
  { id: 'bg_v48', name: 'Inimigo da Hidratação', icon: '🤢', description: 'Bebe água e volta passando mal com 1 min.', category: 'Bagre' },
  { id: 'bg_v49', name: 'Vítima da Linha de Fundo', icon: '🏁', description: 'Sempre sai com bola e tudo.', category: 'Bagre' },
  { id: 'bg_v50', name: 'Rei do Quase Gol... no próprio', icon: '😱', description: 'Tenta tirar e quase mata o próprio goleiro.', category: 'Bagre' },
  { id: 'bg_v51', name: 'Pé de Algodão Amargo', icon: '☁️', description: 'Passes que dão desgosto de ver.', category: 'Bagre' },
  { id: 'bg_v52', name: 'Zumbi do Meio-Campo', icon: '🧟‍♂️', description: 'Vaga pelo campo sem objetivo.', category: 'Bagre' },
  { id: 'bg_v53', name: 'Inimigo do Domínio', icon: '💥', description: 'A bola bate no pé e volta pra trás.', category: 'Bagre' },
  { id: 'bg_v54', name: 'Mestre do Chute de Bico Torto', icon: '📐', description: 'Chuta pra leste, a bola vai pra oeste.', category: 'Bagre' },
  { id: 'bg_v55', name: 'Goleiro de Areia Movediça', icon: '⏳', description: 'Não consegue nem levantar o braço no tempo certo.', category: 'Bagre' },
  { id: 'bg_v56', name: 'Atleta de Vidro Temperado', icon: '🔨', description: 'Parece forte mas quebra na primeira dividida.', category: 'Bagre' },
  { id: 'bg_v57', name: 'Sombra da Própria Ruindade', icon: '👤', description: 'Sua presença diminui o moral do time.', category: 'Bagre' },
  { id: 'bg_v58', name: 'Inimigo da Rapidez', icon: '🐌', description: 'Lento até pra pensar o jogo.', category: 'Bagre' },
  { id: 'bg_v59', name: 'Pé de Ferro Enferrujado', icon: '🧲', description: 'Chega atrasado em todas as divididas.', category: 'Bagre' },
  { id: 'bg_v60', name: 'Mestre da Lamentação Infinita', icon: '🤦', description: 'Erra e fica 5 min reclamando com o vento.', category: 'Bagre' },
  { id: 'bg_v61', name: 'Bagre das Galáxias', icon: '🌌', description: 'Uma ruindade de proporções astronômicas.', category: 'Bagre' },
  { id: 'bg_v62', name: 'Chuteira de Chumbo v2', icon: '👞', description: 'Leva 10 segundos pra dar o primeiro passo.', category: 'Bagre' },
  { id: 'bg_v63', name: 'Inimigo da Coleta', icon: '🧺', description: 'Sempre some na hora de guardar os coletes.', category: 'Bagre' },
  { id: 'bg_v64', name: 'Vítima do Próprio Drible', icon: '🌀', description: 'Se driblou e caiu sozinho.', category: 'Bagre' },
  { id: 'bg_v65', name: 'Passe de Retorno do Mal', icon: '🔙', description: 'Toca pro goleiro na fogueira absoluta.', category: 'Bagre' },
  { id: 'bg_v66', name: 'Dorminhoco de Área', icon: '💤', description: 'O atacante passa do lado e ele tá sonhando.', category: 'Bagre' },
  { id: 'bg_v67', name: 'Mestre da Finalização Fantasma', icon: '👻', description: 'O chute que não existiu.', category: 'Bagre' },
  { id: 'bg_v68', name: 'Inimigo do Centro de Campo', icon: '🚫', description: 'Não pisa no meio nem por decreto.', category: 'Bagre' },
  { id: 'bg_v69', name: 'Bagre de Luxo Subestimado', icon: '💎', description: 'Ruim demais pra ser verdade.', category: 'Bagre' },
  { id: 'bg_v70', name: 'Estátua de Vantablack Quebrada', icon: '🗿', description: 'Cansado e sem utilidade técnica.', category: 'Bagre' },
  { id: 'bg_v71', name: 'Terror do Próprio Time', icon: '😱', description: 'Ninguém quer ele no sorteio.', category: 'Bagre' },
  { id: 'bg_v72', name: 'Pé de Pantufa Furada', icon: '🕳️', description: 'O último nível da escala Bagre.', category: 'Bagre' },

  ...Array.from({ length: 140 }).map((_, i) => ({
    id: `extra-${i}`,
    name: `Conquistador Nível ${i + 1}`,
    icon: '🎖️',
    description: `Atingiu o patamar ${i + 1} de excelência na biqueira.`,
    category: 'Elite' as const
  }))
];

export const MOCK_PLAYERS: Player[] = [];
