
import { Badge, Player, PlayerStatus, Position } from './types';

export const ALL_BADGES: Badge[] = [
  // --- ORIGINAIS & FUNDAMENTAIS ---
  { id: 'b1', name: 'Chegou Agora', icon: '👶', description: 'Acabou de brotar. Fica esperto pra não virar saudade.', category: 'Geral' },
  { id: 'b9', name: 'Sobrevivente', icon: '💀', description: 'Jogou a primeira sem vomitar nem apanhar.', category: 'Geral' },
  { id: 'b2', name: 'Sócio da Boca', icon: '🖐️', description: '5 peladas. Já deve dinheiro pra todo mundo.', category: 'Geral' },
  { id: 'b3', name: 'Procurado', icon: '🚔', description: 'Sumiu. Ou tá preso ou tá devendo pensão.', category: 'Geral' },
  { id: 'b4', name: 'Zumbi', icon: '🧟', description: 'Ressuscitou das cinzas cheio de cachaça.', category: 'Geral' },
  { id: 'b5', name: 'Pulmão de Filtro', icon: '🚬', description: 'Não corre 2 metros, só fica fumando na beira do campo.', category: 'Geral' },
  { id: 'b6', name: 'Perna de Pau', icon: '🪵', description: 'É ruim com força. Dá desgosto de ver.', category: 'Geral' },
  { id: 'b7', name: 'Dono da Várzea', icon: '👑', description: '100 jogos. O fígado já pediu demissão.', category: 'Geral' },
  { id: 'b8', name: 'Chorão', icon: '😭', description: 'Reclama de tudo. Acha que tá na Champions, seu lixo?', category: 'Geral' },
  { id: 'sp_unique_brow', name: 'Brow Único', icon: '/badges/no-monkey.png', description: 'Macacos são proibidos na pelada, mas o brow é UNICO!', category: 'Elite' },
  { id: 'mk1', name: 'Mesmo proibido ele esta presente na pelada', icon: '/badges/no-monkey.png', description: 'Ele viu tudo, mas não vai falar nada. O infiltrado do bueiro.', category: 'Elite' },
  { id: 'dev1', name: 'Mago do Código', icon: '🧙‍♂️', description: 'O mago que fez essa porra toda, o magico da programação', category: 'Architect' },

  // --- PRESENÇA & FIDELIDADE ---
  { id: 'pres1', name: 'Calouro do Bueiro', icon: '👶', description: 'Veio na primeira pelada. Não morreu ainda.', category: 'Geral' },
  { id: 'pres2', name: 'Habitué da Várzea', icon: '🏃', description: '5 jogos confirmados. Já sabe onde é o banheiro.', category: 'Geral' },
  { id: 'pres3', name: 'Sócio-Torcedor', icon: '🎟️', description: '10 jogos. O porteiro já te cumprimenta.', category: 'Geral' },
  { id: 'pres4', name: 'Veterano de Guerra', icon: '🎖️', description: '20 jogos. Já viu muita canelada nessa vida.', category: 'Geral' },
  { id: 'pres5', name: 'Patrimônio Histórico', icon: '🏛️', description: '50 jogos. Faz parte da mobília da pelada.', category: 'Geral' },
  { id: 'pres6', name: 'Estátua de Vantablack', icon: '🗿', description: '100 jogos. Inamovível, lendário, cansado.', category: 'Geral' },
  { id: 'pres7', name: 'Fosforescente', icon: '✨', description: 'Nunca faltou em um mês inteiro.', category: 'Geral' },
  { id: 'pres8', name: 'Coração de Ferro', icon: '❤️', description: 'Veio jogar até debaixo de tempestade.', category: 'Geral' },
  { id: 'pres9', name: 'Inimigo da Folga', icon: '🚫', description: 'Joga até no feriado de Natal.', category: 'Geral' },
  { id: 'pres10', name: 'Turista Espacial', icon: '🚀', description: 'Sumiu por 6 meses e reapareceu do nada.', category: 'Geral' },
  { id: 'pres11', name: 'Vampiro', icon: '🧛', description: 'Só joga se for a pelada da noite.', category: 'Geral' },
  { id: 'pres12', name: 'Bifásico', icon: '🔌', description: 'Joga duas peladas seguidas sem infartar.', category: 'Geral' },
  { id: 'pres13', name: 'Sombra', icon: '👤', description: 'Vem, joga, não fala com ninguém e some.', category: 'Geral' },
  { id: 'pres14', name: 'Arauto do Jogo', icon: '📣', description: 'O primeiro a confirmar no grupo toda semana.', category: 'Geral' },
  { id: 'pres15', name: 'Último dos Moicanos', icon: '🏹', description: 'O último a confirmar, sempre no susto.', category: 'Geral' },
  { id: 'pres16', name: 'Fiel Escudeiro', icon: '🛡️', description: 'Sempre traz um convidado pra completar o time.', category: 'Geral' },
  { id: 'pres17', name: 'Fura-Bolo Profissional', icon: '🎂', description: 'Confirmou e não veio 3 vezes seguidas. Lixo.', category: 'Geral' },
  { id: 'pres18', name: 'Ressuscitado', icon: '✝️', description: 'Voltou a jogar depois de uma lesão de 1 ano.', category: 'Geral' },
  { id: 'pres19', name: 'Onipresente', icon: '🌌', description: 'Está em todas as fotos da galeria, sem exceção.', category: 'Geral' },
  { id: 'pres20', name: 'Viajante do Tempo', icon: '⏳', description: 'Chega sempre 30 min antes da pelada começar.', category: 'Geral' },
  { id: 'pres21', name: 'Atrasado Crônico', icon: '⏰', description: 'O jogo começa às 20h, ele chega às 21h.', category: 'Geral' },
  { id: 'pres22', name: 'Mestre do W.O.', icon: '❌', description: 'Fez o time perder por falta de quórum.', category: 'Geral' },
  { id: 'pres23', name: 'Guerreiro de Segunda', icon: '📅', description: 'Só joga se for na segunda-feira.', category: 'Geral' },
  { id: 'pres24', name: 'Nômade', icon: '🏜️', description: 'Joga em 5 peladas diferentes por semana.', category: 'Geral' },
  { id: 'pres25', name: 'Âncora', icon: '⚓', description: 'Mantém o grupo unido quando todo mundo quer sair.', category: 'Geral' },
  { id: 'pres26', name: 'Frequência 2k', icon: '📻', description: 'Veio em 200 jogos. Sua pele já é sintética.', category: 'Geral' },
  { id: 'pres27', name: 'O Guardião das Chaves', icon: '🔑', description: 'Sempre chega antes do zelador.', category: 'Geral' },
  { id: 'pres28', name: 'Fechador de Porteira', icon: '🔒', description: 'O último a sair do campo em 10 jogos.', category: 'Geral' },
  { id: 'pres29', name: 'Inimigo da Família', icon: '🚫', description: 'Sempre troca o almoço de domingo pelo fut.', category: 'Geral' },
  { id: 'pres30', name: 'Morador do Bueiro', icon: '🏠', description: 'Parece que dorme no centro de treinamento.', category: 'Geral' },
  { id: 'pres31', name: 'Nômade Digital', icon: '💻', description: 'Participa do grupo mesmo quando viaja.', category: 'Geral' },
  { id: 'pres32', name: 'Reserva de Luxo', icon: '🛋️', description: 'Só entra se alguém cansar, mas não falta.', category: 'Geral' },
  { id: 'pres33', name: 'Sombra da Segunda', icon: '🌑', description: 'Aparece toda segunda faça chuva ou faça sol.', category: 'Geral' },
  { id: 'pres34', name: 'Atleta de Cristo', icon: '⛪', description: 'Vem direto do culto pra pelada.', category: 'Geral' },
  { id: 'pres35', name: 'Bebê de Campo', icon: '🍼', description: 'O mais novo da pelada por 5 jogos seguidos.', category: 'Geral' },

  // --- FINANCEIRO & CAIXINHA ---
  { id: 'fin1', name: 'Pagador de Elite', icon: '💳', description: 'Paga a mensalidade antes do ADM cobrar.', category: 'Geral' },
  { id: 'fin2', name: 'Dívida Ativa', icon: '💸', description: 'Deve 3 meses. Tá quase virando dono do campo.', category: 'Geral' },
  { id: 'fin3', name: 'Mãos de Tesoura', icon: '✂️', description: 'Sempre pede desconto pra jogar.', category: 'Geral' },
  { id: 'fin4', name: 'Patrocinador Master', icon: '🏦', description: 'Pagou o churrasco sozinho uma vez.', category: 'Geral' },
  { id: 'fin5', name: 'Inimigo do Pix', icon: '📱', description: 'O celular sempre "trava" na hora de pagar.', category: 'Geral' },
  { id: 'fin6', name: 'Boleto Vencido', icon: '📄', description: 'Vive prometendo pagar "amanhã".', category: 'Geral' },
  { id: 'fin7', name: 'Tesoureiro Assistente', icon: '💰', description: 'Ajuda o ADM a cobrar os outros caloteiros.', category: 'Geral' },
  { id: 'fin8', name: 'Mão Aberta', icon: '🤲', description: 'Pagou a pelada de um amigo que tava sem grana.', category: 'Geral' },
  { id: 'fin9', name: 'Pão Duro de Ouro', icon: '🥖', description: 'Não paga nem a água que bebe.', category: 'Geral' },
  { id: 'fin10', name: 'Magnata da Várzea', icon: '💎', description: 'Sempre traz notas de 100 pra pagar 20 reais.', category: 'Geral' },

  // --- COMPORTAMENTO & RESENHA ---
  { id: 'bh1', name: 'Psicopata do Campo', icon: '🔪', description: 'Briga até com o gandula.', category: 'Geral' },
  { id: 'bh2', name: 'Lobo Solitário', icon: '🐺', description: 'Não passa a bola nem que o mundo acabe.', category: 'Geral' },
  { id: 'bh3', name: 'Coach de Várzea', icon: '📋', description: 'Quer dar tática mas não corre 1 km.', category: 'Geral' },
  { id: 'bh4', name: 'Inimigo da Paz', icon: '🤬', description: 'Xinga o próprio time o tempo todo.', category: 'Geral' },
  { id: 'bh5', name: 'Anjo do Bueiro', icon: '😇', description: 'Pede desculpa depois de dar o rapa.', category: 'Geral' },
  { id: 'bh6', name: 'Fumante de Elite', icon: '🚬', description: 'Fuma um cigarro no intervalo sem cansar.', category: 'Geral' },
  { id: 'bh7', name: 'Sommelier de Cerveja', icon: '🍺', description: 'Entende tudo de breja, nada de bola.', category: 'Geral' },
  { id: 'bh8', name: 'DJ da Pelada', icon: '📻', description: 'Traz a JBL pra tocar pagode sofrido.', category: 'Geral' },
  { id: 'bh9', name: 'Mestre do Churrasco', icon: '🥩', description: 'Joga mal mas faz uma picanha nota 10.', category: 'Geral' },
  { id: 'bh10', name: 'Chorão de Ouro', icon: '😢', description: 'Chorou por um lateral aos 2 min de jogo.', category: 'Geral' },
  { id: 'bh11', name: 'Rei do Mimimi', icon: '🤡', description: 'Acha que tudo é falta.', category: 'Geral' },
  { id: 'bh12', name: 'Fingidor', icon: '🎭', description: 'Cai sozinho e pede pênalti.', category: 'Geral' },
  { id: 'bh13', name: 'Silencioso', icon: '🙊', description: 'Não abriu a boca o jogo inteiro.', category: 'Geral' },
  { id: 'bh14', name: 'Motorista do Time', icon: '🚗', description: 'Traz 4 marmanjos no carro toda semana.', category: 'Geral' },
  { id: 'bh15', name: 'Almoxarife', icon: '🎒', description: 'Sempre traz a bomba e o colete pro jogo.', category: 'Geral' },

  // --- HABILIDADE: ATAQUE (LOG DE FEITOS) ---
  { id: 'atk1', name: 'Matador de Aluguel', icon: '🎯', description: 'Tocou na bola dentro da área? É gol.', category: 'Linha' },
  { id: 'atk2', name: 'Mestre das Canetas', icon: '🖊️', description: 'O rei do bueiro. 3 canetas no mesmo jogo.', category: 'Linha' },
  { id: 'cn1', name: 'Caneteiro Nível 1', icon: '🖊️', description: 'Deu sua primeira caneta oficial.', category: 'Linha' },
  { id: 'cn5', name: 'Caneteiro Nível 5', icon: '🖊️', description: 'Já distribuiu 5 canetas. Tá ficando abusado.', category: 'Linha' },
  { id: 'cn10', name: 'Caneteiro Nível 10', icon: '💉', description: '10 canetas. Os adversários fecham a perna quando você chega.', category: 'Linha' },
  { id: 'cn20', name: 'Caneteiro Nível 20', icon: '🪄', description: '20 canetas. Mestre da mágica entre as pernas.', category: 'Linha' },
  { id: 'cn50', name: 'Lenda das Canetas', icon: '👑', description: '50 canetas. Você é o terror do bueiro.', category: 'Linha' },

  { id: 'ch1', name: 'Dono do Chapéu', icon: '👒', description: 'Deu seu primeiro chapéu oficial.', category: 'Linha' },
  { id: 'ch5', name: 'Chapeleiro Maluco', icon: '🎩', description: '5 chapéus distribuídos. Joga com a bola no alto.', category: 'Linha' },
  { id: 'ch10', name: 'Mestre da Cobertura', icon: '🏠', description: '10 chapéus. Ninguém te alcança por cima.', category: 'Linha' },

  { id: 'db1', name: 'Dibre Humilhante', icon: '🐍', description: 'Deixou o cara no chão e saiu rindo.', category: 'Linha' },
  { id: 'db10', name: 'Entortador de Varal', icon: '🧺', description: '10 dribles desconcertantes confirmados.', category: 'Linha' },

  { id: 'atk4', name: 'Pé de Cristal', icon: '💎', description: 'Dribles finos e chutes precisos.', category: 'Linha' },
  { id: 'atk5', name: 'Artilheiro Raiz', icon: '⚽', description: 'Faz gol de canela, de orelha, de qualquer jeito.', category: 'Linha' },
  { id: 'atk6', name: 'Garçom de Luxo', icon: '🍷', description: '10 assistências em um único mês.', category: 'Linha' },
  { id: 'atk7', name: 'Bicicleta Sem Freio', icon: '🚲', description: 'Tentou uma bike e quase se matou.', category: 'Linha' },
  { id: 'atk8', name: 'Canhão de Vantablack', icon: '💣', description: 'Chute tão forte que furou a rede.', category: 'Linha' },
  { id: 'atk9', name: 'Falso 9', icon: '🕵️', description: 'Ninguém sabe onde ele tá, nem ele mesmo.', category: 'Linha' },
  { id: 'atk10', name: 'Pivô de Ferro', icon: '🏗️', description: 'Segura os zagueiros no peito.', category: 'Linha' },
  { id: 'atk11', name: 'Driblador de Cone', icon: '🚧', description: 'Dribla até a sombra mas não chuta.', category: 'Linha' },
  { id: 'atk12', name: 'Veloz e Furioso', icon: '🏎️', description: 'Só tem corida, zero técnica.', category: 'Linha' },
  { id: 'atk13', name: 'Mestre do Escanteio', icon: '🚩', description: 'Cobrou um escanteio direto pro gol.', category: 'Linha' },
  { id: 'atk14', name: 'Cabeça de Martelo', icon: '🔨', description: 'Ganha todas no alto.', category: 'Linha' },
  { id: 'atk15', name: 'Oportunista', icon: '🦊', description: 'Só faz gol de rebote.', category: 'Linha' },
  { id: 'atk16', name: 'Chute de Mula', icon: '🐴', description: 'Chute forte, sem direção, mas assusta.', category: 'Linha' },
  { id: 'atk17', name: 'Pé de Algodão', icon: '☁️', description: 'Passe tão macio que chega a ser suspeito.', category: 'Linha' },
  { id: 'atk18', name: 'Lobo Solitário IV', icon: '🐺', description: 'Ignorou o companheiro livre pela 10ª vez.', category: 'Linha' },
  { id: 'atk19', name: 'Carrasco do Goleiro', icon: '💀', description: 'Sempre faz gol no mesmo goleiro coitado.', category: 'Linha' },
  { id: 'atk20', name: 'Pé Torto de Ouro', icon: '🥨', description: 'Chutou pra lateral estando na cara do gol.', category: 'Linha' },
  { id: 'atk21', name: 'Mestre do drible curto', icon: '🐍', description: 'Dribla em uma moeda de 1 real.', category: 'Linha' },
  { id: 'atk22', name: 'Cabeça de Ouro', icon: '🥇', description: 'Fez 3 gols de cabeça no mesmo mês.', category: 'Linha' },
  { id: 'atk23', name: 'Fominha de Carteirinha', icon: '🍔', description: 'Ganhou o prêmio fominha 3 vezes.', category: 'Linha' },
  { id: 'atk24', name: 'Garçom sem Gorjeta', icon: '🤵', description: 'Dá o passe e o companheiro erra.', category: 'Linha' },
  { id: 'atk25', name: 'Pé de Vento', icon: '🌪️', description: 'Corre mas a bola fica pra trás.', category: 'Linha' },

  // --- HABILIDADE: DEFESA ---
  { id: 'def1', name: 'Xerife do Bairro', icon: '👮', description: 'Aqui não passa nem vento, imagina atacante.', category: 'Linha' },
  { id: 'def2', name: 'Carrinho de Prata', icon: '🛷', description: 'Mestre do deserto de grama artificial.', category: 'Linha' },
  { id: 'def3', name: 'Muro de Berlim', icon: '🧱', description: 'Ninguém passa no 1 contra 1.', category: 'Linha' },
  { id: 'def4', name: 'Caneleiro de Elite', icon: '🪓', description: 'Bate com classe. O juiz nem vê.', category: 'Linha' },
  { id: 'def5', name: 'Lixeiro do Campo', icon: '🧹', description: 'Limpa todas as jogadas erradas do time.', category: 'Linha' },
  { id: 'def6', name: 'Antiaéreo', icon: '🚀', description: 'Tira todas de cabeça.', category: 'Linha' },
  { id: 'def7', name: 'Sombra do Atacante', icon: '👥', description: 'Marca tão perto que dá pra sentir o hálito.', category: 'Linha' },
  { id: 'def8', name: 'Bifão', icon: '🥩', description: 'Deu um chutão pra lua pra aliviar.', category: 'Linha' },
  { id: 'def9', name: 'Desarmador Atômico', icon: '⚛️', description: 'Tira a bola sem encostar no cara.', category: 'Linha' },
  { id: 'def10', name: 'Zagueiro Construtor', icon: '🏗️', description: 'Sabe sair jogando sem dar chutão.', category: 'Linha' },
  { id: 'def11', name: 'Cadeira Elétrica', icon: '⚡', description: 'O atacante que entra nela sai tremendo.', category: 'Linha' },
  { id: 'def12', name: 'Paredão Humano', icon: '🧱', description: 'Bloqueou 5 chutes no mesmo jogo.', category: 'Linha' },
  { id: 'def13', name: 'Ladrão de Sonhos', icon: '🕵️', description: 'Rouba a bola no último segundo.', category: 'Linha' },
  { id: 'def14', name: 'Caneleiro Poeta', icon: '📜', description: 'Dá rapa mas fala bonito pra não ser expulso.', category: 'Linha' },
  { id: 'def15', name: 'Sombra da Noite', icon: '🌃', description: 'Ninguém vê ele chegando pra desarmar.', category: 'Linha' },
  { id: 'def16', name: 'Xerife de Papel', icon: '🧻', description: 'Acha que marca mas é driblado fácil.', category: 'Linha' },
  { id: 'def17', name: 'Carrapato', icon: '🦟', description: 'Gruda no atacante e não larga mais.', category: 'Linha' },
  { id: 'def18', name: 'Espanta Bolas', icon: '💣', description: 'Só tira a bola com chutão pro alto.', category: 'Linha' },
  { id: 'def19', name: 'Mestre da Antecipação', icon: '🔮', description: 'Chega na bola antes do atacante pensar.', category: 'Linha' },
  { id: 'def20', name: 'Zagueiro Bailarino', icon: '💃', description: 'Tirou a bola com um giro de balé.', category: 'Linha' },

  // --- HABILIDADE: GOLEIRO ---
  { id: 'gl1', name: 'Paredão de Vantablack', icon: '🖤', description: 'Pegou até pensamento hoje.', category: 'Goleiro' },
  { id: 'gl2', name: 'Mão de Alface', icon: '🥬', description: 'Aceitou um frango histórico.', category: 'Goleiro' },
  { id: 'fr1', name: 'Frangueiro Profissional', icon: '🥚', description: 'O primeiro frango a gente nunca esquece.', category: 'Goleiro' },
  { id: 'fr5', name: 'Granja do Bueiro', icon: '🐣', description: '5 frangos confirmados. O time já nem confia mais.', category: 'Goleiro' },
  { id: 'gl3', name: 'Goleiro Voador', icon: '🦅', description: 'Se joga em todas as bolas, até nas fora.', category: 'Goleiro' },
  { id: 'gl4', name: 'Muralha do Crime', icon: '🚧', description: 'Incontestável. Fechou o bueiro.', category: 'Goleiro' },
  { id: 'gl5', name: 'Assustador de Atacante', icon: '👹', description: 'O cara fica com medo de chutar.', category: 'Goleiro' },
  { id: 'gl6', name: 'Lançador de Elite', icon: '🏹', description: 'Coloca o atacante na cara do gol com a mão.', category: 'Goleiro' },
  { id: 'gl7', name: 'Pegador de Pênalti', icon: '🛑', description: 'O pesadelo dos batedores.', category: 'Goleiro' },
  { id: 'gl8', name: 'Goleiro de Boné', icon: '🧢', description: 'Estilo puro, mas a bola passou por baixo.', category: 'Goleiro' },
  { id: 'gl9', name: 'Voz do Time', icon: '🗣️', description: 'Organiza a defesa aos gritos.', category: 'Goleiro' },
  { id: 'gl10', name: 'Elástico Humano', icon: '🤸', description: 'Defesas impossíveis de cinema.', category: 'Goleiro' },
  { id: 'gl11', name: 'Aranha Negra', icon: '🕷️', description: 'Parece ter 8 braços no gol.', category: 'Goleiro' },
  { id: 'gl12', name: 'Pé de Chumbo', icon: '⚓', description: 'Não pula, a gravidade venceu.', category: 'Goleiro' },
  { id: 'gl13', name: 'Grito de Guerra', icon: '📢', description: 'Acorda os vizinhos no grito com a zaga.', category: 'Goleiro' },
  { id: 'gl14', name: 'Mão de Ferro', icon: '✊', description: 'A bola bate e volta, mão duríssima.', category: 'Goleiro' },
  { id: 'gl15', name: 'Goleiro de Churrasco', icon: '🥩', description: 'Veio pro jogo mas tá pensando na carne.', category: 'Goleiro' },
  { id: 'gl16', name: 'Catador de Borboleta', icon: '🦋', description: 'Saiu mal no cruzamento.', category: 'Goleiro' },
  { id: 'gl17', name: 'Muralha de Isopor', icon: '🧊', description: 'Parece forte mas desmorona no primeiro chute.', category: 'Goleiro' },
  { id: 'gl18', name: 'Santo do Bueiro', icon: '😇', description: 'Fez uma defesa milagrosa no último minuto.', category: 'Goleiro' },
  { id: 'gl13', name: 'Handebol', icon: '🤾', description: 'Só defende com o pé, esquece a mão.', category: 'Goleiro' },
  { id: 'gl20', name: 'Goleiro Pipoca', icon: '🍿', description: 'Pula muito mas não pega nada.', category: 'Goleiro' },

  // --- BAGRE & VERGONHA (VITIMAS) ---
  { id: 'bg1', name: 'Bagre de Platina', icon: '🐟', description: 'Atingiu um nível de ruindade sobre-humano.', category: 'Geral' },
  { id: 'vt_cn1', name: 'Passarela de Caneta', icon: '🦵', description: 'Tomou a primeira caneta oficial. Fecha as perna!', category: 'Geral' },
  { id: 'vt_cn5', name: 'Túnel do Metrô', icon: '🚇', description: 'Tomou 5 canetas. Já virou atração turística do bueiro.', category: 'Geral' },
  { id: 'vt_ch1', name: 'Olhou pro Céu', icon: '🪁', description: 'Levou um chapéu e ficou procurando a bola.', category: 'Geral' },
  { id: 'vt_db1', name: 'No Chão', icon: '📉', description: 'Foi driblado e ficou sentado no gramado.', category: 'Geral' },
  { id: 'bg2', name: 'Inimigo da Bola', icon: '🚫', description: 'A bola foge dele como se fosse o diabo.', category: 'Geral' },
  { id: 'bg3', name: 'Tijoleiro', icon: '🧱', description: 'Domina a bola e ela vai pra 2 metros.', category: 'Geral' },
  { id: 'bg4', name: 'Cego de Várzea', icon: '🕶️', description: 'Não viu o companheiro livre do lado.', category: 'Geral' },
  { id: 'bg5', name: 'Perna de Grilo', icon: '🦗', description: 'Não tem força nem pra dar um passe.', category: 'Geral' },
  { id: 'bg6', name: 'Troféu Amigo do Adversário', icon: '🤝', description: 'Deu 3 assistências... pro outro time.', category: 'Geral' },
  { id: 'bg7', name: 'Chuteira de Ouro Invertida', icon: '💩', description: 'Errou 10 gols em uma semana.', category: 'Geral' },
  { id: 'bg8', name: 'Cone de Luxo', icon: '🚧', description: 'Só fica parado olhando o jogo passar.', category: 'Geral' },
  { id: 'bg9', name: 'Dorminhoco', icon: '😴', description: 'Ficou assistindo o contra-ataque acontecer.', category: 'Geral' },
  { id: 'bg10', name: 'O Pior que Já Vi', icon: '🤢', description: 'O ADM chorou vendo ele jogar.', category: 'Geral' },
  { id: 'bg11', name: 'Bagre Atômico', icon: '🧨', description: 'Consegue errar coisas fisicamente impossíveis.', category: 'Geral' },
  { id: 'bg12', name: 'Peixe Fora d\'Água', icon: '🐟', description: 'Parece que esqueceu como corre.', category: 'Geral' },
  { id: 'bg13', name: 'Chuteira de Chumbo', icon: '👞', description: 'Lento demais para o futebol moderno.', category: 'Geral' },
  { id: 'bg14', name: 'Inimigo da Lateral', icon: '↔️', description: 'Consegue cobrar lateral pro adversário.', category: 'Geral' },
  { id: 'bg15', name: 'Tonto Profissional', icon: '😵', description: 'Ficou tonto com o drible do adversário.', category: 'Geral' },
  { id: 'bg16', name: 'Bagre com Grife', icon: '🏷️', description: 'Usa chuteira de 1k mas joga igual um sapato.', category: 'Geral' },
  { id: 'bg17', name: 'Estátua de Sal', icon: '🧂', description: 'Ficou olhando a bola entrar no gol.', category: 'Geral' },
  { id: 'bg18', name: 'Pé de Pantufa de Ouro', icon: '🧸', description: 'Errou 5 chutes fracos no mesmo jogo.', category: 'Geral' },
  { id: 'bg19', name: 'Vítima da Gravidade', icon: '📉', description: 'Caiu sozinho drublando.', category: 'Geral' },
  { id: 'bg20', name: 'Rei do Quase', icon: '🤏', description: 'Quase fez gol, quase desarmou, quase jogou.', category: 'Geral' },

  // --- RESENHA & SOCIAL ---
  { id: 'rs1', name: 'Rádio Pelada', icon: '📻', description: 'Sabe da vida de todo mundo do grupo.', category: 'Geral' },
  { id: 'rs2', name: 'Mestre da Ironia', icon: '😏', description: 'Zoou o bagre com classe.', category: 'Geral' },
  { id: 'rs3', name: 'Organizador Fantasma', icon: '👻', description: 'Ajuda mas nunca aparece na foto.', category: 'Geral' },
  { id: 'rs4', name: 'Fiscal de Mensalidade', icon: '🧐', description: 'Sabe quem não pagou antes do ADM.', category: 'Geral' },
  { id: 'rs5', name: 'Guru da Várzea', icon: '🧘', description: 'Dá conselhos sobre a vida depois do jogo.', category: 'Geral' },
  { id: 'rs6', name: 'Piadista Sem Graça', icon: '🤡', description: 'Conta piada no meio da briga.', category: 'Geral' },
  { id: 'rs7', name: 'Rei do Stickers', icon: '🖼️', description: 'Só fala por figurinhas no Zap.', category: 'Geral' },
  { id: 'rs8', name: 'Inimigo do Silêncio', icon: '🔊', description: 'Não para de falar nem quando tá jogando.', category: 'Geral' },
  { id: 'rs9', name: 'Pacificador', icon: '🕊️', description: 'Separou 5 brigas no mesmo mês.', category: 'Geral' },
  { id: 'rs10', name: 'O Cara da Geladeira', icon: '🧊', description: 'Sempre traz o gelo pro pós-jogo.', category: 'Geral' },

  // --- MANIAS & QUIRKS ---
  { id: 'mn1', name: 'Cheira-Fim-de-Jogo', icon: '👃', description: 'Sempre pergunta "falta quanto?" desde os 5 min.', category: 'Geral' },
  { id: 'mn2', name: 'O Cara do Spray', icon: '💨', description: 'Passa gelol até no cabelo se deixar.', category: 'Geral' },
  { id: 'mn3', name: 'Amigo do Gandula', icon: '🎾', description: 'Ajuda a buscar a bola 10 vezes.', category: 'Geral' },
  { id: 'mn4', name: 'Critico de Chuteira', icon: '👟', description: 'Sabe o modelo da chuteira de todo mundo.', category: 'Geral' },
  { id: 'mn5', name: 'Mestre da Atadura', icon: '🩹', description: 'Enrola 2km de atadura no tornozelo.', category: 'Geral' },
  { id: 'mn6', name: 'Cansado Profissional', icon: '😫', description: 'Pede substituição com 2 min de jogo.', category: 'Geral' },
  { id: 'mn7', name: 'Rei do Arremesso', icon: '👐', description: 'Cobrou 5 laterais perfeitos no peito do time.', category: 'Geral' },
  { id: 'mn8', name: 'Escapista', icon: '🏃', description: 'Sempre foge da hora de recolher os coletes.', category: 'Geral' },
  { id: 'mn9', name: 'O Cara da Garrafinha', icon: '🍼', description: 'Tem a garrafa mais estilosa (e vazia).', category: 'Geral' },
  { id: 'mn10', name: 'Mestre da Lamentação', icon: '🤦', description: 'Errou o passe e deu um soco no chão.', category: 'Geral' },

  // --- TIERS DE CONQUISTA ---
  { id: 'brz1', name: 'Iniciante do Bronze', icon: '🥉', description: 'Fez 1 gol na temporada.', category: 'Elite' },
  { id: 'brz2', name: 'Passador de Bronze', icon: '🥉', description: 'Deu 1 assistência na temporada.', category: 'Elite' },
  { id: 'brz3', name: 'Zagueiro de Bronze', icon: '🥉', description: 'Ganhou 1 jogo na zaga.', category: 'Elite' },
  { id: 'brz4', name: 'Goleiro de Bronze', icon: '🥉', description: 'Fez 1 defesa difícil.', category: 'Elite' },
  { id: 'brz5', name: 'Bronzeado', icon: '🥉', description: 'Participou de 3 peladas seguidas.', category: 'Elite' },
  { id: 'sil1', name: 'Artilheiro de Prata', icon: '🥈', description: 'Fez 10 gols na temporada.', category: 'Elite' },
  { id: 'sil2', name: 'Garçom de Prata', icon: '🥈', description: 'Deu 5 assistências na temporada.', category: 'Elite' },
  { id: 'sil3', name: 'Muralha de Prata', icon: '🥈', description: 'Invicto por 3 jogos seguidos.', category: 'Elite' },
  { id: 'gol1', name: 'Lenda de Ouro', icon: '🥇', description: 'O melhor jogador do mês.', category: 'Elite' },
  { id: 'gol2', name: 'Chuteira de Ouro', icon: '🥇', description: 'Artilheiro absoluto da temporada.', category: 'Elite' },
  { id: 'gol3', name: 'Luva de Ouro', icon: '🥇', description: 'Goleiro menos vazado.', category: 'Elite' },

  // --- QUANTITATIVOS & PROGRESSÃO ---
  { id: 'g1a', name: 'Gofre 1', icon: '⚽', description: 'Primeiro gol marcado.', category: 'Linha' },
  { id: 'g10', name: 'Gofre 10', icon: '🔟', description: '10 gols marcados na história.', category: 'Linha' },
  { id: 'g50', name: 'Gofre 50', icon: '🎖️', description: '50 gols marcados. Artilheiro nato.', category: 'Linha' },
  { id: 'g100', name: 'Gofre 100', icon: '👑', description: 'CENTENÁRIO DO BUEIRO.', category: 'Linha' },
  { id: 'a1', name: 'Garçom 1', icon: '🍷', description: 'Primeira assistência.', category: 'Linha' },
  { id: 'a10', name: 'Garçom 10', icon: '🍷', description: '10 assistências na história.', category: 'Linha' },
  { id: 'a50', name: 'Garçom 50', icon: '🍷', description: '50 assistências. Visão de águia.', category: 'Linha' },

  // --- ESPECIAIS & VANTABLACK ---
  { id: 'vb1', name: 'Essência de Vantablack', icon: '🌑', description: 'Entendeu o espírito da ruindade.', category: 'Architect' },
  { id: 'vb2', name: 'Sombra do Bueiro', icon: '👤', description: 'Vê tudo, ouve tudo, joga nada.', category: 'Architect' },
  { id: 'vb3', name: 'Cavaleiro das Trevas', icon: '🦇', description: 'Joga melhor sob pressão e xingamentos.', category: 'Architect' },
  { id: 'st1', name: 'Gol de Placa', icon: '🏙️', description: 'Fez um gol que merecia placa no bueiro.', category: 'Linha' },
  { id: 'st2', name: 'Defesa do Século', icon: '🧤', description: 'Pegou uma bola que já tava dentro.', category: 'Goleiro' },

  // --- EXTRA GENERATION (PARA GARANTIR 300+) ---
  ...Array.from({ length: 140 }).map((_, i) => ({
    id: `extra-${i}`,
    name: `Conquistador Nível ${i + 1}`,
    icon: '🎖️',
    description: `Atingiu o patamar ${i + 1} de excelência na biqueira.`,
    category: 'Elite' as const
  }))
];

export const MOCK_PLAYERS: Player[] = [];
