/**
 * VANTABLACK INTELLIGENCE - ENGINE EXPANSION (100+ TIERS)
 * Objetivo: Máxima variação no esculacho e na exaltação.
 */

const MORAL_TIERS = [
    { max: 2, text: "{name} é a prova viva de que a natureza erra. No bueiro, ele é o rei do esgoto, um bagre de proporções bíblicas." },
    { max: 4, text: "Olha o {name}, o cara joga como se estivesse com o pé amarrado num botijão de gás. Zero moral, zero futebol." },
    { max: 6, text: "Dizem que o {name} é o segredo do time adversário. Ter ele em campo é jogar com 10 e contra 12." },
    { max: 8, text: "{name} é o tipo de jogador que o juiz dá cartão amarelo só por ele existir. Puramente inútil." },
    { max: 10, text: "A ruindade do {name} é contagiosa. Se ele encosta na bola ela apodrece. É o lixo do asfalto." },
    { max: 12, text: "O {name} tá numa fase que se ele chutar uma manga cai um côco. Moral de centavos e futebol de um real." },
    { max: 14, text: "Bagre supremo. O {name} é aquele cara que só é convidado porque traz a bola, mas hoje nem isso ele fez." },
    { max: 16, text: "{name} tem o carisma de uma porta e o futebol de um cone quebrado. Vergonha da classe dos peladeiros." },
    { max: 18, text: "No dicionário do bueiro, a foto do {name} aparece do lado de 'fracasso'. Um monumento à Bisonhada." },
    { max: 20, text: "O {name} tá jogando com a visão de um morcego ao meio-dia. Não acerta um passe de meio metro." },
    { max: 22, text: "{name} é o autêntico 'nóia da lateral'. Corre muito e não chega em lugar nenhum. Pura pira errada." },
    { max: 24, text: "Moral baixa? Não, o {name} tá no subsolo da dignidade. O futebol dele é um crime ambiental." },
    { max: 26, text: "O pé do {name} parece que foi montado ao contrário. A cada chute é uma lágrima que cai dos olhos da bola." },
    { max: 28, text: "Perna de pau é elogio pro {name}. Ele é uma floresta inteira de madeira podre. Ruim demais!" },
    { max: 30, text: "O {name} é o famoso 'atleta de bar'. Só corre quando o garçom traz a conta. Em campo é um peso morto." },
    { max: 32, text: "Zero técnica, zero raça, 100% de sono. O {name} tá precisando de um choque térmico pra acordar." },
    { max: 34, text: "{name} é o terror do próprio goleiro. A cada recuo é um mini-enfarto na defesa. Perigo constante." },
    { max: 36, text: "O futebol do {name} é tipo sinal de wi-fi na chuva: oscila entre o ruim e o inexistente." },
    { max: 38, text: "Dizem que o {name} joga pelada por recomendação médica, mas o médico deve ser o inimigo dele." },
    { max: 40, text: "{name} é o mestre da invisibilidade. Ninguém vê ele em campo, nem a bola, nem os companheiros." },
    { max: 42, text: "O {name} tem a agilidade de um mamute com artrose. Cada curva é um evento geológico." },
    { max: 44, text: "Moral de bagre esforçado. O {name} até tenta, mas a física e o talento jogam contra ele." },
    { max: 46, text: "{name} tá mais perdido que daltônico em cubo mágico. O posicionamento dele é uma piada." },
    { max: 48, text: "O chute do {name} é tão fraco que a bola para no meio do caminho pra descansar. Triste ver." },
    { max: 50, text: "{name} é o operário do bueiro. Bate, apanha, mas não cria nada. Um robô desregulado." },
    { max: 52, text: "Status: Quase humano. O {name} tá evoluindo pra sair da categoria 'ameba futebolística'." },
    { max: 54, text: "O {name} é o rei do 'quase'. Quase dominou, quase passou, quase foi jogador. Por enquanto, é bagre." },
    { max: 56, text: "Dignidade em construção. O {name} tá tentando não levar caneta toda hora, mas tá difícil." },
    { max: 58, text: "O {name} é aquele cara que só é lembrado na hora de pagar a quadra. Em campo, vira paisagem." },
    { max: 60, text: "Nível mediano de ruindade. O {name} já consegue correr sem tropeçar no próprio cadarço." },
    { max: 62, text: "O futebol do {name} é honesto. Honestamente ruim, mas ele pelo menos corre atrás dos outros." },
    { max: 64, text: "{name} é o garçom do time adversário. Serve passes açucarados pros caras marcarem." },
    { max: 66, text: "Moral oscilante. Num dia o {name} é o Messinho, no outro ele é o Messinho de muletas." },
    { max: 68, text: "O {name} tá com o motor fundido. Meio tempo de jogo e já tá pedindo substituição pra fumar." },
    { max: 70, text: "Bagre de estimação. Todo mundo gosta do {name}, mas ninguém quer ele no seu time." },
    { max: 72, text: "{name} tá começando a entender pra que lado é o gol. A bússola tá começando a funcionar." },
    { max: 74, text: "A vontade é de leão, mas o corpo é de gatinho doméstico. O {name} é raça pura e técnica zero." },
    { max: 76, text: "O {name} é o equilíbrio do caos. Faz uma jogada de craque e três de amador de várzea." },
    { max: 78, text: "Tá saindo da lama! O {name} já não é mais o primeiro a ser escolhido pra ser o café-com-leite." },
    { max: 80, text: "Moral decente. O {name} já impõe um microssegundo de respeito quando pega na bola." },
    { max: 82, text: "{name} é o mestre do básico. Não inventa, porque sabe que se inventar, o desastre é certo." },
    { max: 84, text: "O {name} tá ficando perigoso... pros dois lados. A imprevisibilidade é sua arma secreta." },
    { max: 86, text: "Olho nele! O {name} tá se tornando um coadjuvante de luxo nessa biqueira lotada de bagre." },
    { max: 88, text: "Moral subindo como fumaça de incêndio. O {name} tá começando a ditar o ritmo da bagunça." },
    { max: 90, text: "Respeito moderado conquistado. O {name} já não é mais zoado por causa da chuteira de 20 reais." },
    { max: 92, text: "O {name} tá com o veneno guardado. Só falta a coragem pra destilar ele em campo hoje." },
    { max: 94, text: "{name} é o coração do time. Batendo desregulado, mas ainda tá pulsando com força." },
    { max: 96, text: "A técnica tá querendo aparecer no {name}. É tipo eclipse: raro de ver, mas bonito quando acontece." },
    { max: 98, text: "O {name} tá na porta da elite. Só falta parar de falar tanto e começar a jogar o que sabe." },
    { max: 100, text: "O Ponto Zero. {name} está no equilíbrio dos deuses. O Pelé da várzea em dias de lucidez." },
    { max: 102, text: "A moral passou dos 100! O {name} tá começando a se achar o Neymar do bueiro. Cuidado com o ego." },
    { max: 104, text: "{name} agora joga com o nome na frente. O respeito tá sendo construído gol a gol." },
    { max: 106, text: "O cara tá com a confiança de quem já pagou a dívida do tráfico. {name} joga leve demais." },
    { max: 108, text: "Diferenciado. O {name} já não corre, ele desfila no asfalto quente da pelada." },
    { max: 110, text: "Moral de craque de bairro. O {name} é a referência quando o jogo aperta e o bagre treme." },
    { max: 112, text: "{name} tá numa fase iluminada. Parece que a bola tem um imã no pé desse meliante." },
    { max: 114, text: "Terror dos adversários. Ver o {name} aquecendo é motivo pra muito bagre pedir pra sair." },
    { max: 116, text: "Mestre da caneta seca. O {name} humilha com classe e sai pedindo perdão de brincadeira." },
    { max: 118, text: "O {name} joga com o 'puro ódio'. A bola chora de prazer quando cai no pé dele." },
    { max: 120, text: "Nível acima da média constatado. O {name} é o arquiteto da vitória e o padrinho da resenha." },
    { max: 122, text: "O {name} tá com a visão de águia. Enxerga passe onde só tinha buraco na defesa." },
    { max: 124, text: "Craque com C maiúsculo. O {name} tá jogando o fino, puro suco de talento de várzea." },
    { max: 126, text: "A moral do {name} tá tão alta que ele já tá sendo sondado por outros bueiros da região." },
    { max: 128, text: "{name} é o dono da bola, mesmo quando a bola não é dele. Autoridade máxima em campo." },
    { max: 130, text: "Malandro profissional. O {name} sabe a hora de acelerar e a hora de cozinhar o bagre." },
    { max: 132, text: "{name} tá jogando o que sabe e o que não sabe. Um fenômeno em plena atividade." },
    { max: 134, text: "O cara é um motor V12. Não para, não cansa e ainda esculacha quem tenta marcar o {name}." },
    { max: 136, text: "Puro Vantablack! O {name} brilha na escuridão da ruindade geral. Um farol de gols." },
    { max: 138, text: "Moral de quem manda na biqueira. O {name} fala e o resto baixa a cabeça e joga." },
    { max: 140, text: "Nível lendário desbloqueado. O {name} faz a bola sorrir. O futebol dele é poesia pura." },
    { max: 142, text: "O {name} é a solução para todos os problemas táticos. Só dá a bola nele e vai pro abraço." },
    { max: 144, text: "Visão periférica de 360 graus. O {name} antecipa a jogada antes do bagre pensar." },
    { max: 146, text: "{name} é o terror do esgoto. Onde ele pisa, a grama cresce (ou o asfalto racha)." },
    { max: 148, text: "A moral tá explodindo os medidores. O {name} é o ídolo que essa pelada precisava." },
    { max: 150, text: "Elite Total. O {name} não joga, ele faz mágica com os pés. Um patrimônio do bueiro." },
    { max: 152, text: "Dizem que o {name} inventou o sistema de 3 zagueiros sozinho, só pra ter mais gente pra driblar." },
    { max: 154, text: "O herdeiro legítimo do trono da várzea. {name} joga com terno e gravata na lama." },
    { max: 156, text: "Incontestável. A opinião do {name} sobre o jogo é a única que o juiz respeita." },
    { max: 158, text: "A confiança do {name} é de quem tem as chaves da biqueira e o código do cofre." },
    { max: 160, text: "Gênio incompreendido. O {name} está 10 anos à frente do resto da galera." },
    { max: 162, text: "O {name} é a prova de que Deus tem seus favoritos na hora de distribuir talento." },
    { max: 164, text: "Moral astronômica. O {name} joga como se tivesse controle remoto nos companheiros." },
    { max: 166, text: "Diferenciado é pouco. O {name} é uma anomalia positiva no sistema do futebol ruim." },
    { max: 168, text: "{name} é o imperador do asfalto. Cada passe é uma ordem, cada gol é uma sentença." },
    { max: 170, text: "Nível semideus da biqueira. O {name} faz parecer que o futebol é fácil pra caramba." },
    { max: 172, text: "A aura do {name} intimida o time adversário antes mesmo do apito inicial." },
    { max: 174, text: "O cara é um dicionarista da várzea. Ele inventou todas as gírias e todos os dribles." },
    { max: 176, text: "Moral de titã. O {name} carrega o bueiro nas costas com a ponta do dedinho do pé." },
    { max: 178, text: "A história do {name} será contada pelos bagres pras gerações futuras de pernas de pau." },
    { max: 180, text: "Monstro Sagrado. O {name} já não tem mais nada a provar, só a humilhar quem merece." },
    { max: 182, text: "O {name} é o arquiteto da Matrix do futebol de rua. Ele dobra as leis da física." },
    { max: 184, text: "Puro Luxo Vantablack. O {name} é a joia rara que caiu no meio desse monte de entulho." },
    { max: 186, text: "Respeito total e absoluto. O {name} é o exemplo a ser seguido por quem quer deixar de ser lixo." },
    { max: 188, text: "O {name} é o capitão do navio pirata. Ele lidera a pilhagem de gols com maestria." },
    { max: 190, text: "Lenda Urbana confirmada. Ver o {name} jogar é tipo ver um eclipse: muda sua vida." },
    { max: 192, text: "Moral Divina. O {name} já conversa com os deuses da chuteira velha e furada." },
    { max: 194, text: "O {name} é a personificação da vitória. Onde ele respira, o gol acontece." },
    { max: 196, text: "Soberano do Bueiro. {name} dita as leis, as regras e o placar final." },
    { max: 198, text: "Inalcançável. O {name} atingiu a perfeição na arte de ser o dono da p***a toda." },
    { max: 200, text: "VANTABLACK SUPREMO. {name} é a própria entidade da pelada. Nada escapa ao seu domínio. Ele é o dono do bueiro, o imperador dos pernas de pau. Respeite o soberano." },
];

export const moralService = {
    getMoralCommentary(score: number, name: string): string {
        // Encontrar o tier correspondente
        const tier = MORAL_TIERS.find(t => score <= t.max) || MORAL_TIERS[MORAL_TIERS.length - 1];

        // Substituir placeholder
        return tier.text.replace(/{name}/g, name);
    }
};
